### ISSUE TITLE
"Scroll Based Velocity" Text animation missed dependency

### ISSUE THREAD

**Issue by juanvelozo** [magicuidesign/magicui#100]
![image](https://github.com/magicuidesign/magicui/assets/72322838/bcb107c9-a31d-4706-8aa6-26c7e2689bc9)
Documentation missed you need to install this dependency. 
You can do it with the next command:

```
npm i @motionone/utils
```

You should add this to the docs!

**Comment by dillionverma** [comment]
good idea!

**Comment by dillionverma** [comment]
done

https://github.com/magicuidesign/magicui/commit/cdfb0aa160492eb18e5637ff07e4b5a2fb60a8b5
