### ISSUE TITLE
Magic UI Website: Tweet Card Demo Not Found

### ISSUE THREAD

**Issue by Jimichelle** [magicuidesign/magicui#103]
![Capture d'écran 2024-05-29 163622](https://github.com/magicuidesign/magicui/assets/76010791/9ffda428-01b0-4991-8e2a-a0eaf5b0b8ff)

**Comment by tomonarifeehan** [comment]
The tweet loads for a few seconds and then disappears.


https://github.com/magicuidesign/magicui/assets/20110627/05848d91-656e-4bf7-b321-82a15d19005b

Error:
<img width="1002" alt="Screenshot 2024-06-01 at 1 38 06 AM" src="https://github.com/magicuidesign/magicui/assets/20110627/044edd9e-1a9f-48bf-9689-011b9e1875a2">

**Comment by safethecode** [comment]
@Jimichelle I've uploaded the solution for the issue to the PR. I think the maintainer will check and merge it soon! Please wait

**Comment by dillionverma** [comment]
temp fix added ty everyone!
