### ISSUE TITLE
Unable to access login

### ISSUE THREAD

**Issue by Frainlar** [magicuidesign/magicui#106]
I'm trying to log into Magic UI. 
1. Typed my registered Email address. Clicked Submit button
2. A notification appeared to look into my mailbox for link.
3. After 5 minutes, I got email with link
4. When I clicked on the link, it says the link is expired. 

I tried multiple times but of no success.

**Comment by dillionverma** [comment]
Could you try in a different browser please?

Some people reported this because their cookies were disabled. 

If you try in firefox or safari it might work. Let me know :)

**Comment by dillionverma** [comment]
hey any update on this @Frainlar ?
