### ISSUE TITLE
Light/Dark/System themes breaking

### ISSUE THREAD

**Issue by tscans** [magicuidesign/magicui#108]
Can't seem to explain why this is happening. I've tried this across 4 different browsers with the same issue but first noticed it in Brave. On dark mode, everything appears to be fine. Switching to light mode or system (light) has this weird dark/light mix going on. This is off of the base project after adding a theme changer and favicon change.

<img width="1474" alt="Screenshot 2024-05-30 at 2 51 04 PM" src="https://github.com/magicuidesign/magicui/assets/16454578/b48d5039-7425-4e90-9a47-c002f63b7dc8">

https://www.loom.com/share/3e233e4ceb05473fb2137a9aab9666cd?sid=2606bed2-e78c-4b2c-bf9f-fc693e9867a0

**Comment by dillionverma** [comment]
Thanks for opening this, my team and I will take a look at what's going on here asap

**Comment by itsarghyadas** [comment]
@tscans Is this the `startup` template from your Magic UI Pro that you're using here?

**Comment by tscans** [comment]
@itsarghyadas Yes, its the one I downloaded here: https://pro.magicui.design/docs/templates/startup

I just downloaded a fresh copy of it and tried again. All Ive done was install a shadcn theme toggle that sets the theme via "next-themes".

**Comment by tscans** [comment]
I've tested this in Brave, Chrome, Edge, and Safari. It's the same result across all 4 browsers.

**Comment by dillionverma** [comment]
Pushed fixes @tscans 

![image](https://github.com/magicuidesign/magicui/assets/16860528/26b455d4-2bac-4db9-adb9-f20c6c2dc57c)

Could you please download latest and try again?

https://pro.magicui.design/docs/templates/startup

**Comment by tscans** [comment]
@dillionverma awesome, thanks for the support.
