### ISSUE TITLE
[docs] Better Installation Instructions for all different platforms

### ISSUE THREAD

**Issue by dillionverma** [magicuidesign/magicui#111]
I think some new developers might be confused how to actually use this library. I've had several questions which could just be mitigated by better documentation.

## Questions I've been asked
Question: Where is the framer remix file for these components?
Answer: This library does not work with https://framer.com. It is not a no-code library. These are meant to be used for developers.

Question: How do I install the animated-beam component?
Answer: 
```npx create-next-app@latest my-project --typescript --eslint```
...next steps
```pnpm dev```
...
copy + paste `animated-beam.tsx` to `@/components/magicui/animated-beam.tsx`

Just need better installation docs and FAQs in general tbh. Here's a good reference - https://ui.shadcn.com/docs/installation

**Comment by BankkRoll** [comment]
This is great!! Also suggest better instructions for contributing would be great as well. The [CONTRIBUTING.md](https://github.com/magicuidesign/magicui/blob/main/CONTRIBUTING.md) is great but think a more detailed explanation would help contributors understand the dir structure better.

Example idea below..

1. **Add Sidebar Button Meta for Your Component**  
   File: `config/docs.ts`  
   ```
   // Add sidebar button meta for your component
   ```

2. **Create MDX Page for Your Component**  
   File: `content/docs/components/component.mdx`  
   ```
   // Create MDX page for your component
   ```

3. **Create a Basic Example Showcasing Your Component**  
   File: `registry/components/example/component.tsx`  
   ```
   // Create a very basic example showcasing your component
   ```

4. **Create Your Component**  
   File: `registry/components/magicui/component.tsx`  
   ```
   // Create your component here
   ```

5. **Add Registry Export**  
   File: `registry/index.tsx`  
   ```
   // Add registry export at `const ui: Registry` 
   // Add example export at `const example: Registry`
   ```

**Comment by BankkRoll** [comment]
#118

**Comment by dillionverma** [comment]
done for now
