### ISSUE TITLE
[Questions] How many hours do you invest in this project each day?

### ISSUE THREAD

**Issue by safethecode** [magicuidesign/magicui#115]
@dillionverma 

I have recently taken an interest in this project and have been contributing to it.
There will be various functional improvements, and I'll also be addressing bugs.

By the way, how many hours do you invest in this project each day?

If you have a full-time job and cannot dedicate much time to this project,
how about appointing a moderator? This way, more users might use it.

:)

**Comment by dillionverma** [comment]
Good question @safethecode!

I work on this project full-time everyday haha. Almost 100 hrs a week right now :)

I would LOVE to get a moderator or community manager to just maintain the entire OSS repo! 

My only slight hesitation right now is I'm looking for someone with a strong engineering background who can clean up the mess in this project and take it far!

Code quality + design quality are REALLY important as well and we're lacking a bit in this department atm

Ideally looking for someone who can just take charge of the project and use their own best judgement to do what's best for the community

Let me know if you or someone you know is interested!

**Comment by safethecode** [comment]
@dillionverma 
i am cut out for moderator or  community manager :)

Surprisingly, I have a great interest in this project.
Recently, I've been looking through the code to find ways I can contribute.

I've already implemented this project into my own work!
If the opportunity arises, I would love to participate.

Is there a way to contact you in real-time?
If not, email works for me as well.

**Comment by dillionverma** [comment]
awesome! I just asked the discord channel as well for anyone else interested

dm me on X and we can go from there 

https://x.com/dillionverma

**Comment by dancrump1** [comment]
Definitely excited to contribute some elbow grease! Wish I had more time to fit the slot, but am happy to help where I can

**Comment by unnamed-lab** [comment]
> just

I could work as a community moderator if you'd like.
