### ISSUE TITLE
Sparkle Button ✨ 

### ISSUE THREAD

**Issue by Fxy6969** [magicuidesign/magicui#124]
https://codepen.io/jh3y/pen/LYJMPBL

this would be very cool to be added to button animations, it currently needs to be converted to react.

**Comment by pilladipesh33** [comment]
do you have any idea which can be attach with this at this point I think we should add extra touch with component instead of simply taking codepen design and converting it a react component @dillionverma correct me if I'm wrong

**Comment by dillionverma** [comment]
great suggestion, yes lets make this, yes we can modify it a bit, and yes we should credit the original author in the PR

**Comment by dillionverma** [comment]
Codepens are MIT open source license - https://blog.codepen.io/documentation/licensing/

Same exact license as Magic UI Open Source :)
