### ISSUE TITLE
[text animation] Scroll Based Velocity Text

### ISSUE THREAD

**Issue by dillionverma** [magicuidesign/magicui#13]
A good friend [@ChrisAbdo](https://github.com/ChrisAbdo) has been incredibly kind and given us permission to merge some of his framer motion components into the Magic UI Repo!

This issue requires copying the text animation component from variantvault and adding it to Magic UI.

https://github.com/chrisabdo/motionvariants
https://variantvault.chrisabdo.dev/text-variants

https://github.com/magicuidesign/magicui/assets/16860528/ff329b8f-ed20-4398-830b-9582c86c4ad3

Please refer to #12 for guidelines on how to submit a PR with this new component

**Comment by syedbarimanjan** [comment]
@dillionverma so i just have to copy the component form there and make it work in this repo.

**Comment by dillionverma** [comment]
@syedbarimanjan yessir that's correct! On top of that, need to write a few short docs as well with the required props

**Comment by dillionverma** [comment]
done
