### ISSUE TITLE
Svelte Installation Docs

### ISSUE THREAD

**Issue by gursheyss** [magicuidesign/magicui#131]
Adding some simple installation docs to the already existing svelte installation page

**Comment by engageintellect** [comment]
@gursheyss I

've used MagicUI in Next.js, and it was great... aside from Next's painfully slow hot-reloading.

I'm trying to use it with Sveltekit now... I just installed everything, but the docs say that I am supposed to follow the same directions for using components?

Please advise, I'm a little stuck here...
