### ISSUE TITLE
[docs] Need to fix installation instructions for gauge circle

### ISSUE THREAD

**Issue by dillionverma** [magicuidesign/magicui#133]
<img width="639" alt="image" src="https://github.com/magicuidesign/magicui/assets/16860528/44cd8dd8-8d94-4115-96c7-6fcd57af60f2">
<img width="318" alt="image" src="https://github.com/magicuidesign/magicui/assets/16860528/851a0aa7-fc99-4a66-a080-7f5c4612b306">

we're not writing which filename to save gauge-circle to in the docs

good first issue for new contributors!

**Comment by tomonarifeehan** [comment]
Done. https://github.com/magicuidesign/magicui/pull/138

**Comment by dillionverma** [comment]
merged
