### ISSUE TITLE
[docs] animated beam remove unneeded dependency

### ISSUE THREAD

**Issue by dillionverma** [magicuidesign/magicui#134]
<img width="1014" alt="image" src="https://github.com/magicuidesign/magicui/assets/16860528/8785b9ba-192f-4b99-b1bd-142b489612f0">

<img width="483" alt="image" src="https://github.com/magicuidesign/magicui/assets/16860528/4aa1cb58-1c85-43c2-9902-7188dfc89bb8">

I noticed we have a weird unneeded dependency on radix ui icon props

if we can just remove that entirely it would be easier to use for everyone!

good first issue :)

**Comment by tomonarifeehan** [comment]
@dillionverma Done. https://github.com/magicuidesign/magicui/pull/139

**Comment by dillionverma** [comment]
awesome, closing issue now
