### ISSUE TITLE
[fix] animated subscribe button color fix

### ISSUE THREAD

**Issue by dillionverma** [magicuidesign/magicui#135]
<img width="575" alt="image" src="https://github.com/magicuidesign/magicui/assets/16860528/a3e14382-7416-4fd9-ba32-2f5a7834af57">

seems like animated subscribe button color might not be accessible for all users

we could probably resort to making it the default black / white or some neutral color maybe?

open to suggestions

**Comment by tomonarifeehan** [comment]
Done. https://github.com/magicuidesign/magicui/pull/137

**Comment by alamenai** [comment]
Hi @dillionverma ,

The pull request is merged while the issue is open.

It would be better to link the issue with the PR.

**Comment by dillionverma** [comment]
thanks for the update @alamenai really appreciate it 🙏

closing now
