### ISSUE TITLE
[text animation] Staggered Fade In

### ISSUE THREAD

**Issue by dillionverma** [magicuidesign/magicui#14]
A good friend [@ChrisAbdo](https://github.com/ChrisAbdo) has been incredibly kind and given us permission to merge some of his framer motion components into the Magic UI Repo!

https://github.com/chrisabdo/motionvariants
https://variantvault.chrisabdo.dev/text-variants

This issue requires copying the text animation component from variantvault and adding it to Magic UI.

## Steps
1. Please assign issue to yourself or comment below if you are working on it
2. Please refer to #12 for guidelines on how to submit a PR with this new component

https://github.com/magicuidesign/magicui/assets/16860528/3d2e3b47-c32d-422d-b9bb-d6da00b99bc8

**Comment by shrix1** [comment]
I will work on this

**Comment by shrix1** [comment]
Here is the PR : https://github.com/magicuidesign/magicui/pull/53

**Comment by dillionverma** [comment]
done
