### ISSUE TITLE
NumberTicker value is 0 (First time) Number will not showing

### ISSUE THREAD

**Issue by jackcanscloud** [magicuidesign/magicui#140]
*Next.js

**Comment by itsarghyadas** [comment]
Can you briefly describe what the main issue is?

**Comment by alamenai** [comment]
Hi @jackcanscloud , please could you add to your issue by:

1. Description
2. Steps to reproduce
3. What did you expect?
4. What do you find?
5. Your suggestions to fix the issue

Hi @dillionverma , I would suggest have an issue template and categories to focus on the main issues.

**Comment by dillionverma** [comment]
@alamenai what sort of template do you have in mind? I'm open to setting anything up 

feel free to send suggestions
