### ISSUE TITLE
[Doc]: Refactoring code for Avatar circles component

### ISSUE THREAD

**Issue by alamenai** [magicuidesign/magicui#144]
## Description

This changes refactors the AvatarCircles component to enhance its flexibility and maintainability by allowing dynamic avatar URLs to be passed as props. This change makes the component more reusable and simplifies the code.

## Changes Made:

- [x] Added avatarUrls Prop:

- [x] Introduced a new prop avatarUrls which is an array of strings representing the URLs of the avatars.
- [x] Updated the AvatarCirclesProps interface to include the avatarUrls prop.

## Dynamic Rendering of Avatars:

- [x] Replaced the hardcoded avatar URLs with a .map() function to iterate over the avatarUrls array and render the images dynamically.
- [x] Ensured each image has a unique key and appropriate alt text for accessibility.

## Code Simplification:

- [x] Reduced repetition by eliminating hardcoded image elements.
- [x] Simplified the JSX structure, making it easier to read and maintain.

## Usage Example:

Updated the usage of the AvatarCircles component to pass the avatar URLs as props:

```tsx {4} copy

import AvatarCircles from "@/components/AvatarCircles";

const avatarUrls = [
  "https://avatars.githubusercontent.com/u/16860528",
  "https://avatars.githubusercontent.com/u/29210732",
  "https://avatars.githubusercontent.com/u/20110627",
];

function App() {
  return (
    <AvatarCircles 
      numPeople={5} 
      className="custom-class" 
      avatarUrls={avatarUrls} 
    />
  );
}

export default App;
```

**Comment by alamenai** [comment]
I did not find the code of the provided example to open a pull request.

**Comment by dillionverma** [comment]
This is awesome!! Thanks for adding this :)

Here's a great guide to get started to open a PR

https://github.com/magicuidesign/magicui/blob/main/CONTRIBUTING.md

Let me know if you need any help

**Comment by alamenai** [comment]
Hi @dillionverma ,

Why the code section did not change its code:

![image](https://github.com/magicuidesign/magicui/assets/20143684/c52aad9d-5963-4cec-bc01-bced78a2e8b8)


I changed the `avatar-circles-demo.tsx` like this:

``` tsx copy
import AvatarCircles from "@/registry/components/magicui/avatar-circles";

const avatarUrls = [
  "https://avatars.githubusercontent.com/u/16860528",
  "https://avatars.githubusercontent.com/u/20110627",
];

export default async function AvatarCirclesDemo() {
  return <AvatarCircles numPeople={99} avatarUrls={avatarUrls} />;
}

```

**Comment by dillionverma** [comment]
done
