### ISSUE TITLE
[BUG] Special Effects Particles on mobile

### ISSUE THREAD

**Issue by Sozokujin** [magicuidesign/magicui#148]
The effect works well on desktop and in responsive mode on browsers. But on iPhone, when I scroll down my page, the particles disappear for no reason. Can you help ? Thank you for your help.
Here are some screenshots from my iPhone:
![IMG_0360](https://github.com/magicuidesign/magicui/assets/115474120/bc4d4480-55b9-47d8-b5bc-1ef6002ffac4)
![IMG_0361](https://github.com/magicuidesign/magicui/assets/115474120/c60f02f8-516a-4303-b656-11c2e0f3e498)

**Comment by Sozokujin** [comment]
I tried on an Android device and it seems to work

**Comment by alamenai** [comment]
Hi @Sozokujin , please could you share your code to reproduce the issue in my IPhone?

**Comment by Sozokujin** [comment]
Hi @alamenai, you can find my code at this repo : https://github.com/Sozokujin/portfolio
