### ISSUE TITLE
[Feature]: Create dynamic sound balance component

### ISSUE THREAD

**Issue by alamenai** [magicuidesign/magicui#149]
## Example

![image](https://github.com/magicuidesign/magicui/assets/20143684/6f80345b-cdbd-4a52-b3d1-ab2b9ae093e7)

**Comment by dillionverma** [comment]
do you imagine this automatically moving up and down? do you have a video example @alamenai ?

**Comment by alamenai** [comment]
Hi @dillionverma ,

I would say just a random value for CSS height  that will be changes with `transform` property.

**Comment by dillionverma** [comment]
Here ya go I have the code here

https://github.com/dillionverma/llm.report/blob/main/components/dashboard/LoadingChart.tsx

Do you mind opening a PR to rewrite the code for Magic UI?

I can review and we can get it in this weekend

**Comment by alamenai** [comment]
Thank you @dillionverma ,

Yes, I'll do it this weekend and I'll open another PRs and suggest some features.
