### ISSUE TITLE
[Feature]: Create circular progress indicator like Airbnb progress circle

### ISSUE THREAD

**Issue by alamenai** [magicuidesign/magicui#150]
![image](https://github.com/magicuidesign/magicui/assets/20143684/42201524-b9fa-44b5-92fa-4fa9d8e47b7e)

**Comment by itsarghyadas** [comment]
@alamenai Do you have any idea how to get started with this? It is very cool so if you wanna work on this I would love to assign it to you. Let me know.

Thanks,
Arghya
