### ISSUE TITLE
Error component commandBox in bento. When the page is refreshed, you are teleported directly to the commandBox.

### ISSUE THREAD

**Issue by SkyBLUE62** [magicuidesign/magicui#153]
Hello, I'm currently using the Call To Action 2 component and I wanted to know if it's normal that every time I refresh my page, I'm automatically teleported to this component? If so, how can I disable teleportation to the component ?

But it would appear that the error is due to the command box in the bento component.

https://github.com/magicuidesign/magicui/assets/100870855/cdc2ea6b-d04f-4b64-9405-9ebc9d78d962

**Comment by itsarghyadas** [comment]
`CommandBox` is experiencing issues, and we are working to resolve them with our component.

Thank you,
Arghya
