### ISSUE TITLE
Why Browse Components button redirects to Marquee instead of Bento Grid?

### ISSUE THREAD

**Issue by alamenai** [magicuidesign/magicui#154]
Hi @dillionverma ,

While I was checking the interaction of the component in the landing page, I found that when I click on `Browse Components`, it redirects to the Marquee page instead the first component in the section which is Bendo Grid.

[19b8f05f-c1c1-423a-871c-ff2ed984fc7a.webm](https://github.com/magicuidesign/magicui/assets/20143684/eadbf047-5ca3-4e30-a8a0-3cb4681462fa)

I checked the code of this button but I found it redirects to the components page. I did not figure out what should I change to index to first component.

Any tips from your side to fix it?

**Comment by wbs99** [comment]
Changing the redirects function in next.config.js can optimize this problem but maybe it s not worth a PR if this is worth optimizing I think @dillionverma  can optimize this problem later
![image](https://github.com/magicuidesign/magicui/assets/83934669/c5bae2f7-8754-4389-abe1-3bfc8bce4fe4)

**Comment by alamenai** [comment]
Thank you @wbs99 .

**Comment by dillionverma** [comment]
fixed for now! The default redirect is marquee which is the first component :)
