### ISSUE TITLE
Type of id should be string not id

### ISSUE THREAD

**Issue by alamenai** [magicuidesign/magicui#156]
Hi @dillionverma ,

While I was reading the documentation of Tweet Card, I found you made the type of id is id, however I guess it should be string.

Before I made the changes , I would ask you if that's a mistake:

![image](https://github.com/magicuidesign/magicui/assets/20143684/0a744182-9027-43f3-b12f-2b3a085a575a)

**Comment by itsarghyadas** [comment]
Yes, I just checked the code, and I believe you are correct. We need to change that in the documentation. You can create a PR for it. Do you need me to assign it to you?

Thanks, 
Arghya

**Comment by alamenai** [comment]
Yes, please assign it and I'll update it.
