### ISSUE TITLE
A space should be between digits in Number Ticker

### ISSUE THREAD

**Issue by alamenai** [magicuidesign/magicui#160]
Hi @dillionverma ,

While I was testing the Number Ticker component, I found that the 2 last digits are attached together and there is no space between them:

![986db17d-ad7a-417a-8d5f-a310d2dfbbec](https://github.com/magicuidesign/magicui/assets/20143684/b8f2ed79-03b4-4b65-a3a5-1a04a92590f8)

**Comment by nyxb** [comment]
it need a tracking-wider like this 

```ts
return (
      <span
         className={cn(
            'inline-block tabular-nums text-black dark:text-white tracking-wider',
            className,
         )}
         ref={ref}
      />
   )
```

**Comment by dillionverma** [comment]
merged
