### ISSUE TITLE
Issue: Build Failure Due to Missing ClassName in Ripple Component

### ISSUE THREAD

**Issue by sijirama** [magicuidesign/magicui#168]
When Vercel tried to build the project with the Ripple component, it failed, citing a missing displayName property. I was able to fix this issue by adding the displayName property, but I believe this should be documented for others as well.

![image](https://github.com/magicuidesign/magicui/assets/106167719/c731255b-eac9-4310-8951-e77a1297c343)

![image](https://github.com/magicuidesign/magicui/assets/106167719/40a07f6b-6e37-49b2-b571-405b15599694)

**Comment by dillionverma** [comment]
closing issue since its fixed!
