### ISSUE TITLE
[Bug]: Learn more button in the real components demo section redirect to the home page

### ISSUE THREAD

**Issue by alamenai** [magicuidesign/magicui#178]
## Section:

Real Components Demo

![image](https://github.com/magicuidesign/magicui/assets/20143684/d4e49de6-8f32-42ab-bd0e-91a8b3c99255)

## Scenario

When I click on `Learn more` I expected to be redirected to that component page, however it redirects to the home page.

**Comment by unnamed-lab** [comment]
I believe the behaviour is normal since it's a demo.

**Comment by alamenai** [comment]
@dillionverma , if the behavior is normal, I'll close the issue by the end of the day.

**Comment by dillionverma** [comment]
yeah its just for the demo :) @unnamed-lab is right

although i wonder if there's anything else we can do to make it more intuitive

closing this issue for now though unless anyone has suggestions :)

**Comment by alamenai** [comment]
I would suggest redirect to the page of the component.
