### ISSUE TITLE
Small typo with the dependencies for text animation

### ISSUE THREAD

**Issue by DarKS4ys** [magicuidesign/magicui#185]
![image](https://github.com/magicuidesign/magicui/assets/78923614/a02d8c63-921a-4a6b-bdc3-50ec0d3ccbc1)

The @ is missing at the start of the import, small issue but thought i should point out 😅

**Comment by AmalAbdullaev** [comment]
Check please, i tried to solve this issue
https://github.com/AmalAbdullaev/magicui/pull/1

**Comment by dillionverma** [comment]
fixed on main!

closing issue for now ty for reporting :)
