### ISSUE TITLE
bug: Animated Subscribe Button height change

### ISSUE THREAD

**Issue by jfstn** [magicuidesign/magicui#197]
Hello 👋 

Currently, the Animated Subscribe Button height changes between states.

A video and a couple of screenshots below should illustrate the issue.

https://github.com/magicuidesign/magicui/assets/28389185/cf81fc41-6b86-453d-a696-303210cb28b8

<img width="593" alt="Screenshot 2024-07-07 at 10 43 24" src="https://github.com/magicuidesign/magicui/assets/28389185/67ce4f9f-ce86-40ed-92b8-541f262b9707">
<img width="604" alt="Screenshot 2024-07-07 at 10 43 31" src="https://github.com/magicuidesign/magicui/assets/28389185/3c95cb9e-32dc-4f7b-ba7e-d2c51069b95b">

**Comment by Sahil-Sharma-23** [comment]
@jfstn Your issue is fixed.
@dillionverma Review it once.

**Comment by virus231** [comment]
Not fixed @Sahil-Sharma-23

**Comment by itsarghyadas** [comment]
Correct so basically we have set a fixed height instead of using padding. This issue is fixed.

**Comment by itsarghyadas** [comment]
https://github.com/magicuidesign/magicui/commit/8087fffb20b268623c6309c933bfc0ccf7c50aec
