### ISSUE TITLE
Clicking Learn More on a Component Go to Homepage

### ISSUE THREAD

**Issue by eyalcohen4** [magicuidesign/magicui#199]
https://github.com/magicuidesign/magicui/assets/16276358/9d6c0b50-a7a5-4b24-86fa-f81f4997bbfd

**Comment by binlf** [comment]
They are merely "demo components", they don't/shouldn't take you anywhere specific by design🖖🏽...

**Comment by dillionverma** [comment]
this is a good call out still

it's not intuitive for people at first glance that the components are just demos

we need to make it more clear somehow, or just remove the buttons
