### ISSUE TITLE
[docs]: Need help improving installation docs

### ISSUE THREAD

**Issue by dillionverma** [magicuidesign/magicui#201]
Hey can someone help me write up installation docs for all the major platforms?

It can follow the same structure shown here

https://ui.shadcn.com/docs/installation

Here's a good starting point 

https://github.com/shadcn-ui/ui/tree/main/apps/www/content/docs/installation

<img width="753" alt="image" src="https://github.com/magicuidesign/magicui/assets/16860528/38706506-74ec-4a96-91f9-499de516a540">

we also need to test at least once for each platform to make sure it actually works

i got some reports from some people that they are having difficulties setting up in vite / astro so would love to help them out asap

**Comment by abdrahmanES1** [comment]
@dillionverma  can you assign it to me?
