### ISSUE TITLE
magic-cli add <component> doesn't add to correct components folder

### ISSUE THREAD

**Issue by dreson4** [magicuidesign/magicui#212]
I have shadcn already installed, so I thought I could easily add magicui on top of it, when I run add command it fails to add to src/components folder instead it creates a new folder @ on the root directory.

**To Reproduce**
1. Create a new vite project using bun ``bun create vite my-app``
2. Add shadcn normally
3. In components.json that was already created by shadcn add 
```
  "ui":"@/components/ui",
    "magicui":"@/components/magicui"
```

4. Try to add any magicui component using ``bunx --bun magicui-cli add grid-pattern``

**Expected behavior**
Magicui installs to the current path which is in ``./src/components/magicui`` but instead it creates a new folder ``./@/magicui``

**My other settings**

components.json file
```json
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils",
    "ui":"@/components/ui",
    "magicui":"@/components/magicui"
}
```

tsconfig.json file
```json
 "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
```

Shadcn works just fine, all components are added to @/components/ui but magicui doesn't

I also tried running the magicui cli to init ``bunx --bun magicui-cli init`` it creates a new folder ``./@`` instead, it doesn't see src folder as base folder at all.  Maybe I missed something on the docs, trying to read again and again but nothing works.

**Comment by dillionverma** [comment]
going to cc @rajatsandeepsen here - might have some more insight

**Comment by dreson4** [comment]
My bad, I actually found and fixed the problem. It was my issue
In both my ``tsconfig.js`` and ``tsconfig.app.json`` I had to add 

```
{
  "files": [],
  "references": [
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.node.json"
    }
  ],
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}
```

``compilerOptions baseUrl and paths`` must be at the top and also in the references path for it to work, if it's only top then IDE complains it can't find the files, if it's only in the ``tsconfig.app.json`` file magicUi can't find where to put the components, so the solution ended up being adding in both files ``tsconfig.json`` and ``tsconfig.app.json``

Will close this issue then.

**Comment by tusharsnx** [comment]
I think the docs should also be updated.

> Add the following code to the tsconfig.json **or** tsconfig.app.json file to resolve paths:

I just set up a vite + react project and got this issue. I followed the steps from the official docs.
