### ISSUE TITLE
[fix]: migrate contentlayer.dev to content-collections

### ISSUE THREAD

**Issue by dillionverma** [magicuidesign/magicui#214]
## Context

Contentlayer.dev has been unmaintained for over a year and has lots of old dependencies.

We would benefit from migrating over to something like this https://www.content-collections.dev/docs/quickstart/next which is maintained.

Here are some instructions on how to migrate over
https://www.content-collections.dev/docs/migration/contentlayer

## Requirements
- [ ] Introduce `content-collections` dependency
- [ ] Remove all mention of `contentlayer` and associated dependencies

**Comment by DhruvLamba** [comment]
Can I work on this issue?

**Comment by satwikug25** [comment]
Hi, I am almost done with this task but I am facing some errors, could someone help me out?
P.S: This is my first time working on an open source contribution, so a bit of help would be appreciated

**Comment by satwikug25** [comment]
Also, can you please assign this task to me

**Comment by dillionverma** [comment]
assigned @satwikug25!

do you still need some help with this?

**Comment by Shivraj-K09** [comment]
Hello @dillionverma is this issue fixed? Should i work on this ?

**Comment by dillionverma** [comment]
Fixed with #338
