### ISSUE TITLE
bug: Tooltip component issue in Dock component.

### ISSUE THREAD

**Issue by SwanandD121** [magicuidesign/magicui#217]
**Description of the bug**
When trying to use the `Tooltip` component, an error is thrown: `Tooltip `must be used within `TooltipProvider`. This issue persists only in the **Dock** component.

**To Reproduce**

1. Go to a page or component where the `Tooltip `component is used.
2. Ensure the `Tooltip `is not wrapped within a `TooltipProvider`.
3. Load the page or component.
4. See error: **Tooltip must be used within TooltipProvider.**

**Expected behavior**
The `Tooltip `component should display properly without throwing an error, indicating that it is correctly used within a `TooltipProvider`.

**Screenshots**
Bug:

![image](https://github.com/user-attachments/assets/db7f76e6-b6d3-4670-852b-8ad832b90880)
![image](https://github.com/user-attachments/assets/74a2d4c3-2531-4c97-b0e9-25cd858daf03)

Fix:

![image](https://github.com/user-attachments/assets/9c71e0a0-69f0-4253-bf77-62507e717924)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome

**Additional context**
To resolve this issue, the `Tooltip` component needs to be wrapped within a `TooltipProvider` tag. This will ensure that the `Tooltip `has the necessary context to function correctly.

**Comment by dillionverma** [comment]
thanks for bringing this up! Just pushed a fix for this to main :)

**Comment by SwanandD121** [comment]
> thanks for bringing this up! Just pushed a fix for this to main :)

pleasure :)
