### ISSUE TITLE
Shiny Button animation not visible

### ISSUE THREAD

**Issue by HRDs-VERSE** [magicuidesign/magicui#218]
I am using ShinyButton through the manual method. There is no error in the code, but the animation of the button not appear only text is visible.
![Screenshot 2024-07-13 181622](https://github.com/user-attachments/assets/e15c4846-ada8-4daa-a8eb-1b2eaf5abf79)

**Comment by pilladipesh33** [comment]
can share the photo of code, how you are implementing it?

**Comment by Dom000** [comment]
Same thing with mine , the styles doesn't show up

**Comment by Dom000** [comment]
> can share the photo of code, how you are implementing it?

![Uploading code.png…]()

**Comment by dillionverma** [comment]
Ah look like the issue here is that the --primary css variable is not defined 

This is an issue that needs to be addressed in the code for the component, or we need to make a globals.css file for it and set the --primary variable (similar to the shadcn globals.css file)
