### ISSUE TITLE
[text animation] gradual spacing

### ISSUE THREAD

**Issue by dillionverma** [magicuidesign/magicui#22]
A good friend [@ChrisAbdo](https://github.com/ChrisAbdo) has been incredibly kind and given us permission to merge some of his framer motion components into the Magic UI Repo!

https://github.com/chrisabdo/motionvariants
https://variantvault.chrisabdo.dev/text-variants

This issue requires copying the text animation component from variantvault and adding it to Magic UI.

Please refer to #12 for guidelines on how to submit a PR with this new component

https://github.com/magicuidesign/magicui/assets/16860528/fb46c31f-d13a-4724-8cb9-b88dcc1e7528

**Comment by shrix1** [comment]
Im working on this

**Comment by dillionverma** [comment]
done
