### ISSUE TITLE
[bug] NeonGradientCard

### ISSUE THREAD

**Issue by dong-qian** [magicuidesign/magicui#225]
**Describe the bug**
The glow (blur) effect is not visible on the **mobile browser**, but it displays correctly on desktop devices.

Issue on mobile:
![NeonGradientCard-mobile Medium](https://github.com/user-attachments/assets/73b3886d-0738-4b19-9bbd-95530aa1c915)

**To Reproduce**
1. Go to https://magicui.design/docs/components/neon-gradient-card using the mobile browser
2.  You will see there is no glow effect the card itself

**Expected behavior**
It should be same as desktop

Expect on Desktop
![CleanShot 2024-07-17 at 23 08 49@2x Medium](https://github.com/user-attachments/assets/15967473-c44a-4ad1-9ef0-0aad7ea49dbd)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Macos
 - Browser Chrome
 - Version 126.0.6478.127 

**Smartphone (please complete the following information):**
 - Device: iphone x
 - OS: IOS
 - Browser Chrome
 - Version 126.0.6478.153

**Additional context**
Identified a potential issue and a solution, but need to confirm with the team before moving forward.
Looks like **/3** is the issue,  **/4** or large works.
```
"--after-blur": `${dimensions.width / 3}px`,
```

**Comment by pilladipesh33** [comment]
hi @dong-qian, I checked it the output is quite opposite to what you have mentioned, it works fine.
![Screenshot 2024-08-06 112502](https://github.com/user-attachments/assets/1b0ec689-02d0-4b5a-9207-13b11f985dad)
![Screenshot 2024-08-06 112519](https://github.com/user-attachments/assets/4583a189-a7bc-4f38-bdfe-b20800e26d2d)

**Comment by dillionverma** [comment]
Hi!

I also tested on safari and mobile safari and it seems to work for now

![image](https://github.com/user-attachments/assets/752596fd-56dc-4741-89c1-2bfc0ef4d2f0)

Going to close this issue but if anyone experiences again please feel free to open
