### ISSUE TITLE
[bug]: /docs/components/meteors 

### ISSUE THREAD

**Issue by skehargit** [magicuidesign/magicui#226]
import Meteors from "@/components/magicui/meteors";
error
Failed to resolve import "@/components/magicui/meteors" from "src/components/Home.jsx/Meteor.jsx". Does the file exist?

**Comment by rutdvaj** [comment]
Did you install it through CLI first and have you intialized the components.json file ?

**Comment by skehargit** [comment]
How to do that

**Comment by rutdvaj** [comment]
Firstly do you have a components.json file in your project and make sure you are using typescript

**Comment by skehargit** [comment]
I am using javascript.

**Comment by sdmrf** [comment]
> Firstly do you have a components.json file in your project and make sure you are using typescript

I am having component.json file and using typescript but still showing the same error

**Comment by dillionverma** [comment]
Hi!

I'm chiming in on this to mention that we do have a new cli which can resolve this issue

```bash
npx shadcn@latest add "https://magicui.design/r/meteors"
```

Let me know if this works for you!

Closing the issue for now
