### ISSUE TITLE
Text Reveal Component spliting text props to single characters instead of words when installed through CLI

### ISSUE THREAD

**Issue by moazzam-ali** [magicuidesign/magicui#228]
**Describe the bug**
So in the Text Reveal Component, if installed through CLI it results in a code that splits the input text sentence into single characters for animation instead of words, and treats each characters as a seperate animated element resulting in absurd spacings and abnormal line endings.

Changing the line :  const words = text.split(""); to  const words = text.split(" "); will fix the issue.

It's correct on the manual code section, but if installed through CLI results in the wrong code.

**Comment by Arshia-123** [comment]
I have the same issue and your suggested fix did fix it

**Comment by itsarghyadas** [comment]
@moazzam-ali nice catch! I checked it, and it’s been fixed. Thank you.
