### ISSUE TITLE
in my component the error is showing as declare a component . no doubt this is working properly but not deploying in vercel applications however i have solved it by my self [bug]: /docs/components/confetti

### ISSUE THREAD

**Issue by Abdulrazzak71** [magicuidesign/magicui#230]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Abdulrazzak71** [comment]
![Screenshot (71)](https://github.com/user-attachments/assets/a156b6e4-c5bd-4428-8b77-d5a8eb902c49)

**Comment by dillionverma** [comment]
fixed in latest code since we add displayname
![image](https://github.com/user-attachments/assets/a37509dc-8801-4f30-8e55-983da08a61e5)
