### ISSUE TITLE
[bug]: /docs/components/dock

### ISSUE THREAD

**Issue by arihantjain916** [magicuidesign/magicui#231]
**Describe the bug**
Mode toggle is not working

**Expected behavior**
When click on mode toggle theme have to change, but it does not work

**Comment by prakashsp23** [comment]
have you imported mode toggle component from your own components?

**Comment by arihantjain916** [comment]
Yes, I have copy the mode toggle component code from GitHub and then paste it in my code. I have made some changes in your code and now it working fine..

**Comment by prakashsp23** [comment]
If the problem is solved can you close this issue, thanks.

**Comment by dillionverma** [comment]
any update on this? @arihantjain916

**Comment by arihantjain916** [comment]
No update, toggle is working fine after some changes in code.
I am closing the issue.
Thank you

**Comment by arihantjain916** [comment]
No update, toggle is working fine after some changes in code.
I am closing the issue.
Thank you

**Comment by arihantjain916** [comment]
No update, toggle is working fine after some changes in code.
I am closing the issue.
Thank you
