### ISSUE TITLE
[bug]: /docs/components/meteors

### ISSUE THREAD

**Issue by XTurbo07** [magicuidesign/magicui#243]
In   tailwindcss.config nextjs +  ts project its showing type error in this Code 
 "metor" : {
          "0%": {transform: "rotate(215deg) translateX(0)", opacity: 1},
          "70%": { opacity: 1 },
          "100%": {
            transform: "rotate(215deg) translateX(-500px)",
            opacity: 0,
          },
        }

The error is *Type 'number' is not assignable to type 'string'*

**Comment by itsarghyadas** [comment]
Thank you for directing him in the right direction.

Thanks,
Arghya
