### ISSUE TITLE
[feat]: /docs/components/icon-cloud

### ISSUE THREAD

**Issue by thedanmwangi** [magicuidesign/magicui#247]
**Is your feature request related to a problem? Please describe.**
I think it would be even greater if the Icon Cloud was not just for Icons, but also include Images.

**Describe the solution you'd like**
By passing over an array of URLs of images as props, they could loaded on the cloud and have that very nice aesthetics when displayed.

Great work on Magic UI, a very big fan!

**Comment by itsarghyadas** [comment]
Good idea, but the concern is that this type of component is a bit resource-heavy, and putting high-quality images could make it slower. What use case are you thinking of?

**Comment by thedanmwangi** [comment]
I see. Loading high quality images may prove to be quite the challenge, but it can be mitigated by adding a loader or a preview image.

Its use cases can be limitless. From showing different properties for a real estate SaaS, to different cars for an automotive shop etc.

**Comment by itsarghyadas** [comment]
Here we added the image support https://github.com/magicuidesign/magicui/pull/463 thank you for the feedback.
