### ISSUE TITLE
[bug]: /docs/components/number-ticker

### ISSUE THREAD

**Issue by abello-r** [magicuidesign/magicui#256]
useEffect(
		() =>
			springValue.on("change", (latest) => {
				if (ref.current) {
					ref.current.textContent = Intl.NumberFormat("en-US").format(
						latest.toFixed(0),
					);
				}
			}),
		[springValue],
	);

>> Overload 1 of 3, '(value: number | bigint | StringNumericLiteral): string', gave the following error.
    Argument of type 'string' is not assignable to parameter of type 'number | bigint
    
    Solution:

	useEffect(
		() =>
			springValue.on("change", (latest) => {
				if (ref.current) {
					ref.current.textContent = Intl.NumberFormat("en-US").format(
						Number(latest.toFixed(0)),
					);
				}
			}),
		[springValue],
	);

**Comment by dillionverma** [comment]
fixed in latest!
