### ISSUE TITLE
[bug]: /docs/components/blur-fade

### ISSUE THREAD

**Issue by subhadipbhowmik** [magicuidesign/magicui#260]
**Describe the bug**
When I am trying to make a production build version I am getting this error. 

<img width="959" alt="Screenshot 2024-08-08 144623" src="https://github.com/user-attachments/assets/50ef1142-d5ec-4d54-9747-502c0dfddec0">
**To Reproduce**

1. Install and setup project
2. npm i
3. npm run build
4. See error in terminal

**Expected behavior**
A build for production will be generated. so that i can deploy to server.
**Screenshots**
<img width="959" alt="Screenshot 2024-08-08 144623" src="https://github.com/user-attachments/assets/5a616cbb-9d2b-40bb-9cf4-7eea9214665f">

**Desktop (please complete the following information):**
 - OS: WINDOWS
 - Browser CHROME

**Comment by HydenLiu** [comment]
framer-motion changed the `margin` is type 
about link: https://github.com/framer/motion/pull/2445/files

**Comment by liammc44** [comment]
Good spot @HydenLiu.

To get this working I added the following to my `blur-fade.tsx` file:

```
type MarginValue = `${number}${'px' | '%'}`
type MarginType =
    MarginValue |
    `${MarginValue} ${MarginValue}` |
    `${MarginValue} ${MarginValue} ${MarginValue}` |
    `${MarginValue} ${MarginValue} ${MarginValue} ${MarginValue}`
```

And changed the `BlurFadeProps` interface to now have:
```
inViewMargin?: MarginType;
```

**Comment by HydenLiu** [comment]
> Good spot @HydenLiu.
> 
> To get this working I added the following to my `blur-fade.tsx` file:
> 
> ```
> type MarginValue = `${number}${'px' | '%'}`
> type MarginType =
>     MarginValue |
>     `${MarginValue} ${MarginValue}` |
>     `${MarginValue} ${MarginValue} ${MarginValue}` |
>     `${MarginValue} ${MarginValue} ${MarginValue} ${MarginValue}`
> ```
> 
> And changed the `BlurFadeProps` interface to now have:
> 
> ```
> inViewMargin?: MarginType;
> ```

Yeah, you can use this too @liammc44 
``` 
import { UseInViewOptions } from "framer-motion";

inViewMargin?: UseInViewOptions["margin"];
```

**Comment by stemil23** [comment]
Thanks @HydenLiu!
