### ISSUE TITLE
Is the `async` required in WordFadeIn?

### ISSUE THREAD

**Issue by alamenai** [magicuidesign/magicui#274]
### Code

```tsx
import WordFadeIn from "@/components/magicui/word-fade-in";
 
export async function WordFadeInDemo() {
  return <WordFadeIn words="Word Fade In" />;
}
```

### Documentation

https://magicui.design/docs/components/word-fade-in

**Comment by dillionverma** [comment]
nope not needed! just addressed

**Comment by dillionverma** [comment]
https://github.com/magicuidesign/magicui/commit/29a47fa46414b23db7afb46e4a7fff2faa1ab46a
