### ISSUE TITLE
unable to add new component while on Windows OS

### ISSUE THREAD

**Issue by Not-Sarthak** [magicuidesign/magicui#276]
**Describe the bug**
While trying to add a new component on windows OS, the contentlayer fails and does not detect the path to new component.

**To Reproduce**
Follow the steps given in CONTRIBUTING.md on a Windows Device.

**Expected behavior**
While trying to add a new component, the content layer should recognise the component along with its docs to be added.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version LTS

**Comment by dillionverma** [comment]
This should be fixed now! We migrated from `contentlayer` to `content-collections` recently
