### ISSUE TITLE
[bug]: /docs/components/meteors

### ISSUE THREAD

**Issue by ledung09** [magicuidesign/magicui#278]
**Describe the bug**
Tailwind config error for Meteor

**To Reproduce**
When I paste the code in the document of MagicUI for Meteor effect into tailwind.config.ts, I encounter this problem
![image](https://github.com/user-attachments/assets/4abdabd6-1914-44f3-93aa-852de77c3836)

It said that: Type 'number' is not assignable to type 'string'

**Expected behavior**
The type of "opacity" should be 'string' instead

**Fixing the error**
```
meteor: {
  "0%": { transform: "rotate(215deg) translateX(0)", opacity: "1" },
  "70%": { opacity: "1" },
  "100%": {
    transform: "rotate(215deg) translateX(-500px)",
    opacity: "0",
  },
},
```

**Comment by dillionverma** [comment]
fixed now in new setup!

Meteors uses a string

https://magicui.design/r/index.json

**Comment by ledung09** [comment]
Thank you so much for creating such wonderful UI compont 🙇

**Comment by dillionverma** [comment]
Absolutely:) happy to help! And thanks for your help too
