### ISSUE TITLE
[ Error ] Bento Grid Error

### ISSUE THREAD

**Issue by sayandedotcom** [magicuidesign/magicui#28]
Bento Grid is showing this error  
![image](https://github.com/magicuidesign/magicui/assets/107565578/b54dedf3-319b-45aa-afec-285839eb2eb7)

And why is this component is async in this [example](https://magicui.design/docs/components/bento-grid#:~:text=Expand-,Examples,-Preview)? 
```javascript
export async function BentoDemo() {
  return (
    <BentoGrid className="lg:grid-rows-3">
      {features.map((feature) => (
        <BentoCard key={feature.name} {...feature} />
      ))}
    </BentoGrid>
  );
}
```

**Comment by itsarghyadas** [comment]
Hey @sayandedotcom 

I attempted to reproduce the initial error you encountered, but unfortunately, I couldn't replicate it. I tested it using the example bento grid, and everything seemed to work fine on my end. If you provide more details on how the error was triggered, I might be able to assist you further in troubleshooting.

Regarding the second question, yes you should remove the `async` keyword.

Feel free to reach out if you need any more help or clarification.

Thank you,
Arghya

**Comment by itsarghyadas** [comment]
Hey @sayandedotcom 

I attempted to reproduce the initial error you encountered, but unfortunately, I couldn't replicate it. I tested it using the example bento grid, and everything seemed to work fine on my end. If you provide more details on how the error was triggered, I might be able to assist you further in troubleshooting.

Regarding the second question - Yes you are right! We will remove the `async` keyword as it's not necessary.

Feel free to reach out if you need any more help or clarification.

Thank you,
Arghya

**Comment by sayandedotcom** [comment]
Solved This Issue. The issue was with the "asChild" prop in shadcn Button component.  If I remove it it is working fine! I think it was a problem with shadcn component and  may have occurred because I have an outdated shadcn component ( I added it 1 year ago ).

**Comment by sayandedotcom** [comment]
Imagine what was going through me when I ran into this problem! I I Dmed magicui's founder, created a new repo to test this etc etc 😂
