### ISSUE TITLE
[bug]: /docs/components/sparkles-text

### ISSUE THREAD

**Issue by 0xDynamic** [magicuidesign/magicui#282]
I have installed sparkles-text via CLI and also tried to add it manually, but it just outputs bunch of errors when trying to interact with "d:" and "viewBox" attributes. It does show the text but it doesn't have sparkle animations

![4B6Xg](https://github.com/user-attachments/assets/fa1e3ea2-2ae2-433a-8269-a15b15f52474)

**Comment by wong2** [comment]
same

**Comment by sanjay-mali** [comment]
@0xDynamic Can you explain to me?

**Comment by 0xDynamic** [comment]
> @0xDynamic Can you explain to me?

Whenever I put `<SparklesText text="Magic UI" />` in to use the sparkle text component, it doesn't show the sparkle around the text on website instead it outputs bunch of errors in console like the image I send.

**Comment by sanjay-mali** [comment]
@0xDynamic In my browser working currently. There is no error in the console. 
Try to install using cli. 
```bash
pnpm dlx magicui-cli add sparkles-text
```
Replace pnpm with whatever you use package manager.
If you are using javascript, then it's showing this type of error.

**Comment by sanjay-mali** [comment]
If you can provide a full image of full errors then I make changes upon it.please Ignore my grammar.

**Comment by dillionverma** [comment]
Just installed via cli and tested component with console but found no errors

Proof below

![image](https://github.com/user-attachments/assets/a197af42-9491-4ca7-8f25-c3ccfeb2c5c7)

Will close issue for now unless someone opens up another reproducible example :)

Thanks again!
