### ISSUE TITLE
Is there a property to make the Dock items Not Animated?

### ISSUE THREAD

**Issue by alamenai** [magicuidesign/magicui#283]
Hi @dillionverma,

The new Dock is wonderful but I when I tried it I received feedback from my team if we make it fixed better. 

I checked a documentation, but there is not an example of fixed Dock like the Dock from Figma.

![image](https://github.com/user-attachments/assets/2c294617-c87b-45f0-8e13-e33ae336ad67)

**Comment by patellhett1533** [comment]
there is no specific props related to fixed dock but we can give by classname
```
<Dock
        direction="middle"
        className="fixed bottom-5 left-1/2 -translate-x-1/2"
      >
        .....
      </Dock>
```
using this way we can fixed our dock like figma

**Comment by itsarghyadas** [comment]
@alamenai the main goal of the dock is to have the `"dock-like"` animation. If you’d prefer a fixed look, simply placing those icons in a fixed container with some hover effects should work. As of now, we are not adding any extra props for that. But thanks for the feedback.
