### ISSUE TITLE
[bug]: /docs/components/word-pull-up

### ISSUE THREAD

**Issue by ateendra24** [magicuidesign/magicui#284]
**Describe the bug**
In the Word Pull Up component of the MagicUI library, each character is wrapped individually instead of wrapping entire words. This occurs because the code splits the string by each character due to the line "{words.split("")". Issue arises while adding the component using the command _npx magicui-cli add word-pull-up_ but it is not in github repo. 

**To Reproduce**

1. Go to a page using the Word Pull Up component from the MagicUI library.
2. Add a string of text to be animated by the component.
3. Render the component on the page.
4. Notice that each character of the string is wrapped separately, rather than wrapping words as expected.
5. Expected behavior
6. The Word Pull Up component should wrap entire words instead of individual characters, maintaining the readability and flow of the text.

**Screenshots:**
_Before correction_
![image](https://github.com/user-attachments/assets/3614b803-c3af-43fe-a650-f79818121403)

_After correction_
![image](https://github.com/user-attachments/assets/50dce6f0-9036-43ec-b35a-8b9403857efc)

**Desktop:**
OS: Windows 11
Browser: Chrome. Firefox, Brave
Version:  Chrome- 127.0.6533.122 , Firefox- 129.0.2, Brave- 1.69.153

**Additional context**
The issue was resolved by manually modifying the code to split the string by spaces rather than individual characters, using "{words.split(" ")}" instead of "{words.split("")}".
To fix this we need to update the behaviour when we add the component using the command  _npx magicui-cli add word-pull-up_ .

**Comment by itsarghyadas** [comment]
@ateendra24 sorry for the late reply. The issue has been fixed, and we’re now using the `shadcn` CLI approach. We’re also combining all similar text-animation components into one component so you can import a single file and reuse it for multiple animation styles.
