### ISSUE TITLE
Dock component misses the events properties

### ISSUE THREAD

**Issue by alamenai** [magicuidesign/magicui#292]
Hi @dillionverma ,

I started using the Dock component and when I wanted to attach onClick event, I found that it misses this in its properties.

##Screenshot

![image](https://github.com/user-attachments/assets/1ca32807-0abb-4d01-9de4-415cbceeeca0)

## Current

```
Type '{ children: Element; className: string; onClick: () => void; }' is not assignable to type 'IntrinsicAttributes & DockIconProps'.
  Property 'onClick' does not exist on type 'IntrinsicAttributes & DockIconProps'.ts(2322)
```

## Expected 

Possibly to add events to the Dock component.

**Comment by dillionverma** [comment]
thanks!!!

just fixed in latest pr
