### ISSUE TITLE
[bug]: /docs/components/flickering-grid

### ISSUE THREAD

**Issue by javeed-syed** [magicuidesign/magicui#293]
**Describe the bug**
While adding this component, component is not adding only a example is adding

**To Reproduce**
1. npx magicui-cli add flickering-grid
2. Instead of component in components/magicui, it is creating only components/example folder

**Expected behavior**
to create a component in magicui folder

**Comment by dillionverma** [comment]
thanks for pointing this out! should be fixed by this

https://github.com/magicuidesign/magicui/commit/ebfb9332e13ba139a7f95cbefbdd715a170eb1e1
