### ISSUE TITLE
Documentation component

### ISSUE THREAD

**Issue by Syntax3rror404** [magicuidesign/magicui#295]
**Is your feature request related to a problem? Please describe.**
I want to add my documentation nativly to the website. 

**Describe the solution you'd like**
A template or component that allows you to add markdown as documentation. 

**Describe alternatives you've considered**
Just add the content as native text but a component for this specific usecase will look definitly better

**Additional context**
Im pro user :D

**Comment by dillionverma** [comment]
Thanks for the request!

We can start adding a few small components for this, but for a full-featured solution I might recommend https://fumadocs.vercel.app/

They've done a phenomenal job with their implementation :)
