### ISSUE TITLE
Impressum/Cookie settings/site

### ISSUE THREAD

**Issue by Syntax3rror404** [magicuidesign/magicui#296]
**Is your feature request related to a problem? Please describe.**
To be legal fine we need a impressum and cookie settings. 

**Describe the solution you'd like**
A component for the impressum and the other one for setting an checking the cookies. 

**Describe alternatives you've considered**
Difficult.

**Comment by dillionverma** [comment]
Hi! Thanks for adding this issue. Although it's important I think it's outside the scope of this project which is to create animated components for landing pages. I would recommend maybe using v0.dev for help with creating a component like this!
