### ISSUE TITLE
[bug]: Component AnimatedGradientText not working properly

### ISSUE THREAD

**Issue by gbrasil720** [magicuidesign/magicui#297]
**Describe the bug**
While using this component, component is not working correctly

**To Reproduce**
1. npx magicui-cli add animated-gradient-text
2. Add the AnimatedGradientText component to an app page

**Expected behavior**
To gradient work properly as it shows in docs. Something like this:
![image](https://github.com/user-attachments/assets/9c288a9f-f32f-4b52-8afe-fddc0e4a1b2d)

**Screenshots**
This is what I get from the component:
![image](https://github.com/user-attachments/assets/58ba844b-2105-4439-bbb4-90649856ecea)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Arc
 - Version: Latest (09/03/2024)

**Additional context**
In the component its possible to see a tailwind variant called `--bg-size`, that is not declared anywhere

**Comment by KiranPolaki** [comment]
hello @gbrasil720  works fine for me. have you updated "tailwind.config.js" like mentioned in the install steps

**Comment by gbrasil720** [comment]
Hey @KiranPolaki ,

I just descovered what was going on, i installed magic ui after installing shadcn/ui. I created another project just installing magic and works fine. Thanks
