### ISSUE TITLE
Flickering grid resizing doesn't work

### ISSUE THREAD

**Issue by aidendotgg** [magicuidesign/magicui#300]
**Describe the bug**
The flickering grid component doesn't resize when the page resizes so for example if you are on a phone and then flip your screen the grid will be the wrong size

**To Reproduce**
1. add flickering grid component to your project with no pre defined width or height
2. resize screen to be bigger

**Comment by itsarghyadas** [comment]
Can you describe a little more so I can quickly understand the issue?

**Comment by ignSKRRRTT** [comment]
> Can you describe a little more so I can quickly understand the issue?

Not really sure how else you want me to describe it. I stated what was wrong and how to reproduce it.

**Comment by ignSKRRRTT** [comment]
Here is a video showing off the issue. When I make the screen bigger the flickering grid doesn't get bigger with it. It only corrects itself when I refresh. https://i.e-z.host/files/0gpy9fap.mp4

**Comment by nunihalawi** [comment]
Also having this issue

**Comment by dillionverma** [comment]
this issue was fixed with https://github.com/magicuidesign/magicui/pull/416
