### ISSUE TITLE
File Tree - [aria-*] attributes do not have valid values

### ISSUE THREAD

**Issue by PrizemArtNFT** [magicuidesign/magicui#303]
**Describe the bug**

Run a lighthouse audit for accessibility on the file tree component and you will see all files are highlighted as [aria-*] attributes do not have valid values. I believe this could be caused by aria-expanded="true" on files. 

![image](https://github.com/user-attachments/assets/4e390eb2-23ad-4d93-ac33-07294b3c9bc5)

**To Reproduce**
1. Go to https://magicui.design/docs/components/file-tree in chrome
2. Run a light house audit
3. Wait for results
4. Scroll to Accessibility  errors

**Expected behavior**

No accessibility error on file tree component.

**Comment by dillionverma** [comment]
fixed!
