### ISSUE TITLE
[Doc]: The first component should be Hero Video Dialog after clicking components link

### ISSUE THREAD

**Issue by alamenai** [magicuidesign/magicui#304]
Hi @dillionverma ,

After you added the HVD component, it seems you forgot to target it as the first component when the users click on the components link.

### Current

Marquee

### Expected

Hero Video Dialog

**Comment by sanjay-mali** [comment]
Hey!
Can you review my pull request? I just changed the order of component items. If anything else, then tell me.
Thanks.
