### ISSUE TITLE
[bug]: Interactive Icon Cloud glitching 

### ISSUE THREAD

**Issue by gbrasil720** [magicuidesign/magicui#306]
**Describe the bug**
The component starts glitching and not moving correctly

**To Reproduce**
1. npx magicui-cli add icon-cloud
2. Use the component on any page
3. See the glitch

**Expected behavior**

https://github.com/user-attachments/assets/65ab36fd-7d78-48bd-a7c9-63693f2b4157

**Screenshots**

https://github.com/user-attachments/assets/d742f6e5-ff33-4dfc-b69f-622902ecff0b

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Arc
 - Version: Latest version

**Comment by itsarghyadas** [comment]
Did you check it in another browser to see if it works?

**Comment by gbrasil720** [comment]
> Did you check it in another browser to see if it works?

I did! Tried Edge, Firefox, Brave, etc. Not working in any of these. Don't know what I can do now, for now I removed the component from my project
