### ISSUE TITLE
[CRITICAL] Simple deploy on vercel, not works

### ISSUE THREAD

**Issue by miguelgargallo** [magicuidesign/magicui#309]
![image](https://github.com/user-attachments/assets/33145111-f45a-4e89-be73-07cf0ca28c93)

**Comment by miguelgargallo** [comment]
Just tap the button to deploy from description, nothing more.

**Comment by dillionverma** [comment]
Just tested again and it works!
![image](https://github.com/user-attachments/assets/a64ed68c-cf95-49dd-bc28-05bca29c84b2)
