### ISSUE TITLE
Shimmer button animation not working correctly when using "important" Tailwind setting

### ISSUE THREAD

**Issue by rafaponieman** [magicuidesign/magicui#315]
When the`important` setting is set ot true in the Tailwind config, Instead of going all the way around, the shimmer gets almost to the end and returns back. I tried tweaking the Tailwind animation settings but couldn't get it to work.

I know the important use case is not that common, in our case, we have to use it temporarily while Tailwind lives along another UI library we'll later drop.

![Screencast_20240913_132316](https://github.com/user-attachments/assets/a8dcc126-84e0-47f5-b60d-8a6aa7c18224)

Thanks a lot!

**Comment by notREKASH** [comment]
I tested the shimmer, and I couldn't reproduce the issue you're describing. Could you share your code so I can take a closer look? It's a bit challenging to identify the problem without seeing the actual implementation.

**Comment by itsarghyadas** [comment]
Why and where are you using `important`? I just tested it in a fresh environment, it worked fine and I have failed to reproduce the issue.

**Comment by rafaponieman** [comment]
@notREKASH, @itsarghyadas, thank you for taking the time to test it. It looked to me like this issue would happen regardless of my specific implementation, so I didn't think of testing it on a fresh install, which I probably should have, sorry!

Regarding the `important` setting, we're using it because we're migrating from MUI to Tailwind in stages, so they have to work alongside for a while and the `important` setting helps a lot. We'll remove it once the transition is complete.

Given that you were unable to reproduce the issue, it looks like there is another unrelated interaction in my application that comes into effect with the `important` setting (maybe with MUI). It's a large application so I can't share code, but I'll run a few tests on my side and will let you know if I do find an actual issue. Thank you.
