### ISSUE TITLE
[bug]: /docs/components/animated-list

### ISSUE THREAD

**Issue by gokh4nozturk** [magicuidesign/magicui#333]
**Describe the bug**

**To Reproduce**
1. Go to [animated-list](https://magicui.design/docs/components/animated-list)
2. See error

**Expected behavior**
"When the number of elements runs out, it's expected that the animation stops."

**Screenshots**

https://github.com/user-attachments/assets/302b9df3-8c35-40e9-954e-cee6b252f681

**Comment by itsarghyadas** [comment]
@gokh4nozturk Do you have a record of the after changes you have made? that would be helpful.

**Comment by itsarghyadas** [comment]
Thanks. now it is implemented.
