### ISSUE TITLE
Adding Background that requires Framer Motion. 

### ISSUE THREAD

**Issue by Gitstar-OC** [magicuidesign/magicui#340]
**Is your feature request related to a problem? Please describe.**
I have made a custom background component [here](https://mindect.vercel.app/test) in both dark and light theme.

**Describe the solution you'd like**
Is there a way I could contribute that to magic UI. It would be cool if magic ui can add this. I have made severel colors and background for single light background component. But the caveat here is that it is made in framer motion, is there a way this can be added.

**Before directly removing the issue or commenting first checkout -> https://mindect.vercel.app/test

**Describe alternatives you've considered**
N / A

**Additional context**

Screenshot of animated background 

1. In dark theme 
![Screenshot 2024-09-28 162354](https://github.com/user-attachments/assets/2d4cf373-61cf-4ff1-b471-3893963e0864)

2. In light theme 
![Screenshot 2024-09-28 162512](https://github.com/user-attachments/assets/0c8ab1b3-69e3-4d6b-b5cf-3050c7ff5d4b)

**Comment by dillionverma** [comment]
Looks awesome! We could definitely use something like this

Feel free to follow the contributing guide here to open a PR for this

Will be closing the issue for now

https://github.com/magicuidesign/magicui/blob/main/CONTRIBUTING.md
