### ISSUE TITLE
[bug]: /docs Page not found

### ISSUE THREAD

**Issue by besscroft** [magicuidesign/magicui#344]
**Describe the bug**
Click the button to jump to a page that does not exist

**To Reproduce**
1. Go to '[https://magicui.design/docs](https://magicui.design/docs)'
2. Click on 'React.js button'
3. See error

**Expected behavior**
According to the original rules, it should now be changed to the `Next.js` button.

**Screenshots**
![image](https://github.com/user-attachments/assets/4e155860-43ef-4834-844e-466149c96afa)
![image](https://github.com/user-attachments/assets/df9fa6c9-b8dc-411b-b738-6b374c09e0aa)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Vishalll07** [comment]
I guess they must not have added the page for it

**Comment by dillionverma** [comment]
ah the page was renamed to /manual

closing this issue since it's addressed now!
