### ISSUE TITLE
[feat]: /docs/installation      React installation direct guide

### ISSUE THREAD

**Issue by VanshGolakiya-2910** [magicuidesign/magicui#357]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by VanshGolakiya-2910** [comment]
In the installtalltion section of the website there used to be a installation for react but now there is only for "NEXT JS" please add the components for React
![image](https://github.com/user-attachments/assets/d04db7f2-3d20-40bd-a4d1-907773eeea44)

**Comment by dillionverma** [comment]
React installation guide is here!

https://magicui.design/docs/installation/manual
