### ISSUE TITLE
[Bug] /docs/components/rainbow-button

### ISSUE THREAD

**Issue by subhadip001** [magicuidesign/magicui#359]
**Bug Description**
While passing custom classNames with the New Rainbow button component it removes/ overrides the animation

**To Reproduce**
1. Install the new Rainbow button with CLI
2. Use it in project (Animation will show)
3. Add className to it as props
4. Notice the button becomes animationless

**Expected behavior**
While using with the className props like this
`<RainbowButton className="p-2 flex gap-2">{children}</RainbowButton>;`
It should combine with the animation.

**Screenshots**
<img width="131" alt="Screenshot 2024-10-06 at 4 01 10 PM" src="https://github.com/user-attachments/assets/1d3a4b2a-a936-4e84-b0ce-963fbf02caab">

**Desktop (please complete the following information):**
 - OS - MacOs
 - Browser - chrome
 - Version 129.0.6668.90

**Additional context**
Btw I have figured it out and solved the issue for my project. If needed i can fix this also.

**Comment by dillionverma** [comment]
thanks for pointing this out! just pushed a fix for this in latest commit :) 

https://github.com/magicuidesign/magicui/commit/33b2067637337995102817e3b5c03178d0b9f448
