### ISSUE TITLE
[bug]: /docs/components/animated-shiny-text

### ISSUE THREAD

**Issue by 0xRudeboy** [magicuidesign/magicui#362]
**Describe the bug**

**To Reproduce**
1. Navigate to https://magicui.design/docs/components/animated-shiny-text
3. Scroll down to the ***manual installation*** source code and the ***tailwind.config.js***
4. See misspelled error

**Additional context**
the animation out of the box is not working when using the manual installation guide because there is a misspelled variable within the AnimatedShinyText that does not match up with the tailwind.config.js file configuration

AnimatedShinyText component
```jsx
<p
      style={
        {
          "--shiny-width": `${shimmerWidth}px`,
        } as CSSProperties
      }
      className={cn(
        "mx-auto max-w-md text-neutral-600/70 dark:text-neutral-400/70",
 
        // Shine effect
        "animate-shiny-text bg-clip-text bg-no-repeat [background-position:0_0] [background-size:var(--shiny-width)_100%] [transition:background-position_1s_cubic-bezier(.6,.6,0,1)_infinite]",
 
        // Shine gradient
        "bg-gradient-to-r from-transparent via-black/80 via-50% to-transparent  dark:via-white/80",
 
        className,
      )}
    >
      {children}
    </p>
```

tailwind.config.js file configuration
```javascript
animation: {
        "shiny-text": "shiny-text 8s infinite",
      },
      keyframes: {
        "shiny-text": {
          "0%, 90%, 100%": {
            "background-position": "calc(-100% - var(--shimmer-width)) 0",
          },
          "30%, 60%": {
            "background-position": "calc(100% + var(--shimmer-width)) 0",
          },
        },
      },
```

In the component the variable is named "shiny-width" as opposed to the tailwind config where the variable is named "shimmer-width" rendering the animation non functional

**Comment by itsarghyadas** [comment]
This is fixed now and thanks for the contribution.
