### ISSUE TITLE
[feat]: /docs/components/hyper-text

### ISSUE THREAD

**Issue by nav2924** [magicuidesign/magicui#369]
Is your feature request related to a problem? Please describe.
I'm frustrated when elements don't have animations upon scrolling, which limits the user experience and makes the UI feel less dynamic.

Describe the solution you'd like
I'd like to add an animateOnScroll feature, allowing elements to animate as they appear in the viewport when users scroll down the page. This feature would increase interactivity and create a more engaging visual experience for users.

Describe alternatives you've considered

Manually adding animations using custom JavaScript solutions.
Utilizing third-party libraries such as AOS (Animate on Scroll) or ScrollReveal, though integrating them with the current setup requires additional configuration.
Additional context
Here is an example of the kind of animation effect that could be implemented: [Include a relevant screenshot, GIF, or video link if needed].
This feature would enhance the responsiveness and aesthetics of the website, improving user engagement.

**Comment by nav2924** [comment]
Is your feature request related to a problem? Please describe.
I'm frustrated when elements don't have animations upon scrolling, which limits the user experience and makes the UI feel less dynamic.

Describe the solution you'd like
I'd like to add an animateOnScroll feature, allowing elements to animate as they appear in the viewport when users scroll down the page. This feature would increase interactivity and create a more engaging visual experience for users.

Describe alternatives you've considered

Manually adding animations using custom JavaScript solutions.
Utilizing third-party libraries such as AOS (Animate on Scroll) or ScrollReveal, though integrating them with the current setup requires additional configuration.
Additional context
Here is an example of the kind of animation effect that could be implemented: [Include a relevant screenshot, GIF, or video link if needed].
This feature would enhance the responsiveness and aesthetics of the website, improving user engagement.****

**Comment by dillionverma** [comment]
Hi! Are there particular components you want to see animations on scroll for? Let me know as we already have animations on scroll for component we feel it's necessary like the `TextReveal` for example.

Closing issue for now until response
