### ISSUE TITLE
[bug]: /docs/components/rainbow-button

### ISSUE THREAD

**Issue by nmrisrl11** [magicuidesign/magicui#375]
**Describe the bug**
I'm trying to install rainbow-button using CLI on my NextJS app. 

My current folder structure:
src/app/[locale]/globals.css

I think by default when installing some MagicUI component this is all fine when there's no need to do some adjustments specially on globals.css. 

But on my case with my current folder structure this will results an error because the current globals.css will not be found.

I know I can just manually just update some of my codes to make it work. But it would be better if the CLI installation setup can be flexible no matter where the globals.css file is. (is it possible?)

**To Reproduce**
1. Install rainbow-button using CLI (must be the same folder structure with me)
2. Just scroll down to see the error 

**Expected behavior**
Just like other MagicUI components, ready to use just using CLI.

**Screenshots**
![image](https://github.com/user-attachments/assets/bdfdc21d-db5d-4fec-a73d-cdcc3ba912ea)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version: 1.70.126

**Comment by nav2924** [comment]
You can temporarily move or create a copy of your globals.css file at the default expected location (src/globals.css) before running the installation. After the installation, you can move the file back to its original location or manually update the references in the installed package.

**Comment by nmrisrl11** [comment]
> You can temporarily move or create a copy of your globals.css file at the default expected location (src/globals.css) before running the installation. After the installation, you can move the file back to its original location or manually update the references in the installed package.

Nice and yes this work around will work as well. But my concern here is it would be better if the installation of component (i.e. rainbow-button) will be done with just CLI. No need to do some extra steps, if the case is like mine.

**Comment by dillionverma** [comment]
Hi!

This issue can be resolved by updating the `components.json` to point to the correct location of your css file.

For example

```json
{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "new-york",
  "rsc": true,
  "tailwind": {
    "config": "tailwind.config.js",
    "css": "app/globals.css",
    "baseColor": "neutral",
    "cssVariables": true
  },
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils"
  }
}
```

Here's a more detailed guide https://ui.shadcn.com/docs/components-json
