### ISSUE TITLE
[BUG] Dock component: useTransform

### ISSUE THREAD

**Issue by jercomio** [magicuidesign/magicui#376]
For Next.js (latest) application, there is a bug because the property `mouseX` is undefined (line 86, dock.tsx). See the declare function `useTransform` in `index.d.ts`file. `input: MotionValue<I>` must be an array like the example : `const z = useTransform([x, y], ([latestX, latestY]) => latestX * latestY)`

So, to resolve this bug, write `mouseX = []` instead of `mouseX`.

```ts
const DockIcon = ({
  size,
  magnification = DEFAULT_MAGNIFICATION,
  distance = DEFAULT_DISTANCE,
  mouseX = [],
  className,
  children,
  ...props
}: DockIconProps) => {
  const ref = useRef<HTMLDivElement>(null);

  const distanceCalc = useTransform(mouseX, (val: number) => {
    const bounds = ref.current?.getBoundingClientRect() ?? { x: 0, width: 0 };

    return val - bounds.x - bounds.width / 2;
  });
```

**Comment by Willy-Bueno** [comment]
@jercomio You probably didn't pass ```"use client"```  in your page or component. If you pass a fazio array it should probably work, but you will lose the effects of the dock.

**Comment by maq796113** [comment]
I have fixed the bug

**Comment by rafai123** [comment]
Thanks all

**Comment by itsarghyadas** [comment]
Hey this issue is now fixed with this PR https://github.com/magicuidesign/magicui/pull/454
