### ISSUE TITLE
[bug]: /docs/components/marquee 

### ISSUE THREAD

**Issue by SGOD-pro** [magicuidesign/magicui#378]
**Describe the bug**
the marquee cards was not moving

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dillionverma** [comment]
make sure you add animation keyframes to tailwind config

or join our discord for community help 

https://magicui.design/discord
