### ISSUE TITLE
[Bug]: Registry schema mis-redirect from shadcn CLI

### ISSUE THREAD

**Issue by Lenghak** [magicuidesign/magicui#382]
**Describe the bug**
The registry of the url `https://magicui.design/r/index.json` has redirected to `https://magicui.design/r/styles/default/index.json.json`
This prevent the new shadcnCLI from getting the correct components and failed installation process for magic ui.

**To Reproduce**
1. Go to `https://magicui.design/r/index.json`
2. See error

**Expected behavior**
The registry url should output the correct json file for CLI to correctly install the components

**Screenshots**
The screenshot showed the error page with the url after requesting to the `https://magicui.design/r/index.json` from web browser

![image](https://github.com/user-attachments/assets/921fb8e7-1984-49f2-a3f7-cb28097812bb)

**Desktop (please complete the following information):**
 - OS: Linux Nobara (Fedora 40)
 - Browser: Brave
 - Version 1.71.114

**Comment by dillionverma** [comment]
Fixed! Thanks for pointing this out

https://magicui.design/r/index.json
