### ISSUE TITLE
[Component] Scroll Progress Bar

### ISSUE THREAD

**Issue by iacopo-schianchi** [magicuidesign/magicui#386]
[Scroll progress bar example](https://www.w3schools.com/howto/howto_js_scroll_indicator.asp)

### Requirements
- [ ] Display scroll progress in web page
- [ ] Should be customizable with props (e.g. color, border radius, smoothness, height)

![image](https://github.com/user-attachments/assets/3e8b0c62-f8f9-4ff5-a4b4-96a97da1c0cb)

**Comment by iacopo-schianchi** [comment]
I would be willing to make this.

**Comment by dillionverma** [comment]
linking #177

**Comment by itsarghyadas** [comment]
We just merged this component with this PR https://github.com/magicuidesign/magicui/pull/177. Closing this issue.
