### ISSUE TITLE
[bug]: /docs/templates/portfolio

### ISSUE THREAD

**Issue by Aryankpoor** [magicuidesign/magicui#389]
**Describe the bug**
Blur fade text returns an error wile building the nextjs project

**To Reproduce**
1. Download the portfolio template
2. Run `npm run build`
3. You will receive an error in `./src/components/magicui/blur-fade.tsx`
4. `Type error: Type 'string' is not assignable to type 'MarginType | undefined'.`

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/eb60367e-c84a-4bb8-9ac5-40fdfc16a334)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rohannY** [comment]
- Add `import { UseInViewOptions } from "framer-motion";`
- Add the line `type MarginType = UseInViewOptions["margin"];`
- Replace `inViewMargin?: string` with `inViewMargin?: MarginType;`

**Comment by Aryankpoor** [comment]
Yep that fixed it! I think the .`zip` file should be updated on the website with this change.

**Comment by Aryankpoor** [comment]
I think the .`zip` file should be updated on the website with this change.
