### ISSUE TITLE
Failed to run locally

### ISSUE THREAD

**Issue by pilladipesh33** [magicuidesign/magicui#39]
**localhost:3000 Error**
![240523_13h38m35s_screenshot](https://github.com/magicuidesign/magicui/assets/99866329/fd80b43e-0118-48c7-8a85-0d760384726d)

**Terminal Log**
![240523_13h47m32s_screenshot](https://github.com/magicuidesign/magicui/assets/99866329/79656989-9fc5-4763-8b51-f085d1fc22b7)

So, I'm new to magicui community I have forked the project and follow the step in `contribution.md` but after running the project I was facing this error I wasn't able to find out the ERROR can some help me fixing this

**Comment by Shatlyk1011** [comment]
hi. I had the same issue. To fix this, go several commits back, and try to rerun the app

**Comment by shrix1** [comment]
Same issue, please help @dillionverma

**Comment by pilladipesh33** [comment]
> hi. I had the same issue. To fix this, go several commits back, and try to rerun the app

Can you elaborate more please

**Comment by Shatlyk1011** [comment]
> > hi. I had the same issue. To fix this, go several commits back, and try to rerun the app
> 
> Can you elaborate more please

just for testing purpose, go 5 commits back using `git reset ` or `git checkout`, then try to run the app. it will work

**Comment by bernaferrari** [comment]
Yeah, wavy text is bugged

**Comment by fediralydev** [comment]
hey someone fixed this?

**Comment by abdrahmanES1** [comment]
the problem fixed by @dillionverma on this commit https://github.com/magicuidesign/magicui/commit/4e6f568520af3c8aa9b7bf9fc6ccdf0fe99f24c9 
and i add documenttaion o the default object in the https://github.com/magicuidesign/magicui/commit/d187eb59acf73b43e41fbfc082082ccf0c44b570
try to get pull the new changes

**Comment by unnamed-lab** [comment]
I am experiencing something different when trying to run after dependency installation.
Can someone please help me check it out? 🙏🏾

[Failure working locally](https://github.com/magicuidesign/magicui/issues/50)

**Comment by dillionverma** [comment]
hey @pilladipesh33 ! This issue should be fixed in most recent commit :) I updated the mdx file to make sure the object has backticks

**Comment by dillionverma** [comment]
closing
