### ISSUE TITLE
[bug]: /docs/components/orbiting-circles

### ISSUE THREAD

**Issue by techwithmanuel** [magicuidesign/magicui#393]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I can't seem to install any component

**Comment by dillionverma** [comment]
Please refer to our installation instructions for each framework here https://magicui.design/docs/installation

Closing issue for now!
