### ISSUE TITLE
Accordian Component for Magic UI

### ISSUE THREAD

**Issue by Gitstar-OC** [magicuidesign/magicui#399]
**Is your feature request related to a problem? Please describe.**
This feature request is an addition to the MagicUI library of components

**Describe the solution you'd like**
I have a component at https://prompt-a-thon.vercel.app/ which takes various inputs and props as speed, opacity and other things. I am thinking of adding this component to magic ui after making it more better.

**Describe alternatives you've considered**
N/A

**Additional context**
Please visit https://prompt-a-thon.vercel.app/ to see the accordian component, it does not look very well in design and can be improved.

**Comment by dillionverma** [comment]
Hi! 

Thanks for bringing this to our attention. I think this component is outside the scope of Magic UI for now since Magic UI is solely focused on making components for landing pages. Perhaps might be a better fit in the future if we update our scope!

- Dillion
