### ISSUE TITLE
[feat]: /docs/components/blur-fade

### ISSUE THREAD

**Issue by akyndev** [magicuidesign/magicui#418]
**Is your feature request related to a problem? Please describe.**
 No

**Describe alternatives you've considered**
I would love it if you could add the fade in horizontal to blur fade, such that they can fade in left, right, up, and down

**Comment by itsarghyadas** [comment]
@akyndev like a `props` for `left|right|up|down`?

**Comment by itsarghyadas** [comment]
![chrome_jYFEkE3hdX](https://github.com/user-attachments/assets/0c2f36ac-6ea0-4cbb-9487-3f12b92f3039)

something like this? It contains all the 4 directions. Please take a look and let me know.

**Comment by itsarghyadas** [comment]
https://github.com/magicuidesign/magicui/pull/455 added the props for the 4-way direction. Thanks for the feedback.
