### ISSUE TITLE
Website 'solarflarehq' in Showcase Section is No Longer Available

### ISSUE THREAD

**Issue by moroii69** [magicuidesign/magicui#421]
**Describe the bug**  
The website 'solarflarehq' listed under the Showcase section is no longer available or deployed.

**To Reproduce**  
1. Go to the website's Showcase section.
2. Find 'solarflarehq' listed there.
3. Attempt to access the website.
4. See that the website is no longer accessible.

**Expected behavior**  
The website should be accessible/removed as part of the Showcase section.

**Screenshots**  
![image](https://github.com/user-attachments/assets/0f624424-ebeb-4ec9-b4ee-eb35310812c4)
![image](https://github.com/user-attachments/assets/2912e555-4574-4b4d-a9b3-95f436967d57)
![image](https://github.com/user-attachments/assets/72e23daa-79f4-4393-a700-90cb6ee10400)

**Desktop (please complete the following information):**  
- OS: Windows 11  
- Browser: Brave  
- Version: Brave is up to date (Version 1.73.91)

**Smartphone (please complete the following information):**  
- Device: N/A  
- OS: N/A  
- Browser: N/A  
- Version: N/A

**Additional context**  
This website appears to have been closed or is no longer deployed. Please remove or update the link.

**Comment by dillionverma** [comment]
Fixed! https://github.com/magicuidesign/magicui/commit/71e52fb5423fe04b91290c8bc8635757fd5e15aa

Thanks for opening issue
