### ISSUE TITLE
[bug]: /docs/components/marquee

### ISSUE THREAD

**Issue by lokendra-singh-rao** [magicuidesign/magicui#425]
**Describe the bug**
Facing eslint error @typescript-eslint/no-explicit-any
![image](https://github.com/user-attachments/assets/dc7ebd7c-ca11-403f-98e1-597137932920)

**To Reproduce**
1. Add component
2. Create build

**Expected behavior**
The marque component provided should not have any type. Please specify specific types.

**Screenshots**
![image](https://github.com/user-attachments/assets/c3447f87-f629-40b5-9a3d-b487b832f214)
Here is the error in component, instead we can put unknown type

**Desktop (please complete the following information):**
 - Doesn't matter

**Comment by dillionverma** [comment]
Fixed! https://github.com/magicuidesign/magicui/commit/95a620f21b6696b52229ac3d5113b04de90edcb6
