### ISSUE TITLE
[feat]: /docs/components/number-ticker - StartValue

### ISSUE THREAD

**Issue by dinbtechit** [magicuidesign/magicui#426]
**Is your feature request related to a problem? Please describe.**
Always starts from zero. It would be nice if we can provide a starting value

**Describe the solution you'd like**
```html
<NumberTicker startValue={50} value={100} />
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by PraveenShinde3** [comment]
Can you please assign it to me?

**Comment by dinbtechit** [comment]
@PraveenShinde3  - Could you also address the value with commas, or would that be a separate issue?

**Comment by PraveenShinde3** [comment]
I have made a change, so that we can give a custom "start value" 

For example : in following demo i have set the startValue to "500" and value to "1000" and for decimal the startValue is "3.99" and value to "8.67"

https://github.com/user-attachments/assets/780c256e-df2f-4701-af3d-ba3b1c27cc40

**Comment by PraveenShinde3** [comment]
@dinbtechit what exactly is the issue with commas?

**Comment by dinbtechit** [comment]
> @dinbtechit what exactly is the issue with commas?

Oh I did not realize. The comma's were already taken care of. I am curios what does it look like for large numbers...

```jsx
<NumberTicker startValue={'168,500.10'} value={'170,500.99'}  
```

**Comment by PraveenShinde3** [comment]
this is how it looks as per your given startValue and value

the code would be something like this 
`<NumberTicker startValue={168500.1} value={170500.99} decimalPlaces={2} />`


https://github.com/user-attachments/assets/10b30bd3-e4ef-436d-801a-febd827c2c3a

**Comment by dinbtechit** [comment]
> this is how it looks as per your given startValue and value
> 
> the code would be something like this `<NumberTicker startValue={168500.1} value={170500.99} decimalPlaces={2} />`
> 
>  Screen.Recording.2024-11-29.210929.mp4

That looks freaking good!! Great job! thanks @PraveenShinde3

**Comment by PraveenShinde3** [comment]
Hoping this PR gets approved 🤞

**Comment by itsarghyadas** [comment]
Hey, we discussed this and decided not to add props like that for now. Instead, we plan to set a custom duration for each `numberTicker` component so they can finish at their own pace (or simultaneously) if needed. Thanks for the feedback! If we decide to add this props in the future, we'll reopen the discussion.

**Comment by Tanaykmr** [comment]
@itsarghyadas any idea by when the custom duration will be implemented?
Was looking for that specific feature that led me here.

If you could assign that to me, that would be great.
