### ISSUE TITLE
[max-width: 70vh]: /docs/components/icon-cloud

### ISSUE THREAD

**Issue by vishalqalandari903** [magicuidesign/magicui#429]
**Describe the bug**
In the canvas tag of the icon-cloud component, the max-width is set to 70vh instead of 70vw. so it's becoming smaller which people may not want.

**To Reproduce**
1. Add component in react
2. Reduce height or width of page
3. the size of component will change.

**Expected behavior**
there should be option because the className or style props are not working and it's not the solution to put max-width to 70vh because many may not want it in their website

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser [chrome]

**Comment by mazipan** [comment]
It is coming from 3rd party lib `react-icon-cloud`, as you can see in: https://github.com/teaguestockwell/react-icon-cloud/blob/master/src/renderers/cloud.tsx#L90

**Comment by itsarghyadas** [comment]
It is coming from 3rd party lib. But did/can you try to override it?

**Comment by itsarghyadas** [comment]
I checked it and found out that this component has an additional prop:

```js
canvasProps: {
    style: {
      width: "100%",
      height: "100%",
    },
},
```
So like this you can change the height and width based on you preferences and this will update the `canvas` component.

You can add this after the `containerprops`

![image](https://github.com/user-attachments/assets/d0bbc514-e6a1-4003-b890-7191f0acd56c)

Thank you for the feedback.
