### ISSUE TITLE
Hypertext should use IntersectionObserver for mobile device support

### ISSUE THREAD

**Issue by mazipan** [magicuidesign/magicui#431]
**Is your feature request related to a problem? Please describe.**

Current implementation of `HyperText` is using `onMouseEnter` which not available in the Mobile Device. when the `animateOnLoad={false}`, use Intersection Observer to start the animation.

<img width="697" alt="Screenshot 2024-12-02 at 16 43 49" src="https://github.com/user-attachments/assets/c5765d2d-2246-437e-836a-3564171a972f">

**Describe the solution you'd like**

You can check on https://usehooks-ts.com/react-hook/use-intersection-observer to see how to create intersection observer helper.

**Additional context**

To maintain the backward compatibility, please keep the `onMouseEnter` as it is.

**Comment by itsarghyadas** [comment]
@mazipan So, if I understand correctly, you want that text to animate when it comes into view? on Desktop the hover will trigger the effect and on mobile when your scrolling down to that part the animation will trigger for once?

**Comment by mazipan** [comment]
Yes, correct.
In the current condition, the animation seems never executed, especially if the element below the fold where user needs to scroll down to see the element.
There is no option in the mobile device to see the animation in that condition.

**Comment by itsarghyadas** [comment]
Makes sense. Than you for the catch. Will push a fix soon 🤝

**Comment by itsarghyadas** [comment]
@mazipan this should be fixed now 🤝 thanks for the feedback.
