### ISSUE TITLE
[bug]: /docs/components/animated-beam

### ISSUE THREAD

**Issue by jasonaw98** [magicuidesign/magicui#433]
**Describe the bug**
Encountered Typescript error:
![image](https://github.com/user-attachments/assets/873551f2-19e7-4c89-a10d-805bb17a6b04)

Type 'RefObject<HTMLDivElement | null>' is not assignable to type 'RefObject<HTMLElement>'.
  Type 'HTMLDivElement | null' is not assignable to type 'HTMLElement'.
    Type 'null' is not assignable to type 'HTMLElement'.ts(2322)
animated-beam.tsx(10, 3): The expected type comes from property 'containerRef' which is declared here on type 'IntrinsicAttributes & AnimatedBeamProps'

devDependencies:
"typescript": "^5.7.2",
"@types/node": "^22.10.1",
"@types/react": "^19.0.1",
"@types/react-dom": "^19.0.1",

**To Reproduce**
1. Go to 'https://magicui.design/docs/components/animated-beam'
2. Click on installation via CLI
3. Install and run npx shadcn@latest add "https://magicui.design/r/animated-beam"

**Expected behavior**
A typescript error:

Type 'RefObject<HTMLDivElement | null>' is not assignable to type 'RefObject<HTMLElement>'.
  Type 'HTMLDivElement | null' is not assignable to type 'HTMLElement'.
    Type 'null' is not assignable to type 'HTMLElement'.ts(2322)
animated-beam.tsx(10, 3): The expected type comes from property 'containerRef' which is declared here on type 'IntrinsicAttributes & AnimatedBeamProps'

**Screenshots**
<img width="691" alt="image" src="https://github.com/user-attachments/assets/46d054ea-c2bd-4730-b26b-347078b238e0">

**Desktop (please complete the following information):**
 - OS: MacOS Sequoia
 - Browser Chrome

**Additional context**
Suggest to add these changes to animated-beam.tsx

  containerRef: RefObject<HTMLElement | null>; // Container ref
  fromRef: RefObject<HTMLElement | null>;
  toRef: RefObject<HTMLElement | null>;

**Comment by jasonaw98** [comment]
Created a PR for a patch fix for this issue here https://github.com/magicuidesign/magicui/pull/434

**Comment by dillionverma** [comment]
merged!
