### ISSUE TITLE
[feat]: /docs/components/word-pull-up

### ISSUE THREAD

**Issue by KeithPrakash** [magicuidesign/magicui#438]
**Is your feature request related to a problem? Please describe.**
  this animations happens on  document load

**Describe the solution you'd like**
better to add a feature to enable scroll on animation to word pull up

**Describe alternatives you've considered**

**Additional context**

**Comment by itsarghyadas** [comment]
Hey, so if I understand correctly, you want that part to animate when it comes into view?

**Comment by KeithPrakash** [comment]
Yess its what I wanted..

**Comment by dillionverma** [comment]
Hi! This issue has been addressed :) We added a new prop called `startOnView` which triggers animation when in view.

Let me know if this works for you!

**Comment by KeithPrakash** [comment]
Thank you
