### ISSUE TITLE
[bug]: /docs/components/rainbow-button

### ISSUE THREAD

**Issue by Yao-lin101** [magicuidesign/magicui#439]
![c02a929b-73bf-46d0-b1db-310c8d88dc55](https://github.com/user-attachments/assets/789a8876-e321-4c95-9944-16d9c3e2ce1c)
![3d34976b-df45-4d10-ba3a-d4105501bee4](https://github.com/user-attachments/assets/c9db0e10-573e-47e7-b915-1e80453e8ca8)
I used the component and did not see the expected animation and rainbow effect; I should have correctly configured my tailwind.config.js.

**Comment by dillionverma** [comment]
What css do you see when you right-click and inspect on the button? Do the classes show up? Do the css animations show up?

**Comment by Yao-lin101** [comment]
![QQ20241214-124529](https://github.com/user-attachments/assets/4c74247a-c6db-438c-9de8-cf886a3649b3)


Thank you very much for your reply. I found that the edge of this button indeed plays a flowing animation, but it does not emit a rainbow effect. Below is the style I copied from the browser:
    --color-1: 0 100% 63%;
    --color-2: 270 100% 63%;
    --color-3: 210 100% 63%;
    --color-4: 195 100% 63%;
    --color-5: 90 100% 63%;
    --gradient-from: #ff2975;
    --gradient-to: #00FFF1;
    --gradient-config: 35%;
    --gradient-from-transparent: rgba(255, 41, 117, 0.15);
    --gradient-to-transparent: rgba(0, 255, 241, 0.15);
    --tw-bg-opacity: 1;
    --tw-border-spacing-x: 0;
    --tw-border-spacing-y: 0;
    --tw-translate-x: 0;
    --tw-translate-y: 0;
    --tw-rotate: 0;
    --tw-skew-x: 0;
    --tw-skew-y: 0;
    --tw-scale-x: 1;
    --tw-scale-y: 1;
    --tw-pan-x: ;
    --tw-pan-y: ;
    --tw-pinch-zoom: ;
    --tw-scroll-snap-strictness: proximity;
    --tw-gradient-from-position: ;
    --tw-gradient-via-position: ;
    --tw-gradient-to-position: ;
    --tw-ordinal: ;
    --tw-slashed-zero: ;
    --tw-numeric-figure: ;
    --tw-numeric-spacing: ;
    --tw-numeric-fraction: ;
    --tw-ring-inset: ;
    --tw-ring-offset-width: 0px;
    --tw-ring-offset-color: #fff;
    --tw-ring-color: rgb(59 130 246 / 0.5);
    --tw-ring-offset-shadow: 0 0 #0000;
    --tw-ring-shadow: 0 0 #0000;
    --tw-shadow: 0 0 #0000;
    --tw-shadow-colored: 0 0 #0000;
    --tw-blur: ;
    --tw-brightness: ;
    --tw-contrast: ;
    --tw-grayscale: ;
    --tw-hue-rotate: ;
    --tw-invert: ;
    --tw-saturate: ;
    --tw-sepia: ;
    --tw-drop-shadow: ;
    --tw-backdrop-blur: ;
    --tw-backdrop-brightness: ;
    --tw-backdrop-contrast: ;
    --tw-backdrop-grayscale: ;
    --tw-backdrop-hue-rotate: ;
    --tw-backdrop-invert: ;
    --tw-backdrop-opacity: ;
    --tw-backdrop-saturate: ;
    --tw-backdrop-sepia: ;
    --tw-contain-size: ;
    --tw-contain-layout: ;
    --tw-contain-paint: ;
    --tw-contain-style: ;
    box-sizing: border-box;
    position: relative;
    display: inline-flex;
    height: 2.75rem;
    animation: rainbow var(--speed, 2s) infinite linear;
    cursor: pointer;
    align-items: center;
    justify-content: center;
    border-radius: 0.75rem;
    background-image: linear-gradient(#121213,#121213),linear-gradient(#121213 50%,rgba(18,18,19,0.6) 80%,rgba(18,18,19,0)),linear-gradient(90deg,hsl(var(--color-1)),hsl(var(--color-5)),hsl(var(--color-3)),hsl(var(--color-4)),hsl(var(--color-2)));
    background-size: 200%;
    padding-left: 2rem;
    padding-right: 2rem;
    padding-top: 0.5rem;
    padding-bottom: 0.5rem;
    font-weight: 500;
    transition-property: color, background-color, border-color, text-decoration-color, fill, stroke;
    transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
    transition-duration: 150ms;
    background-clip: padding-box,border-box,border-box;
    background-origin: border-box;
    border: calc(0.08 * 1rem) solid transparent;

**Comment by dillionverma** [comment]
Hmm interesting so the animation style is indeed there on the button `animation: rainbow var(--speed, 2s) infinite linear;
` but the issue might be related to the keyframes?

It also might possibly be related to your project not picking up tailwind config changes? Have you tried clearing node module and/or updating tailwind version?

If you can make a reproducible codesandbox of this that would also help! https://codesandbox.io

**Comment by Yao-lin101** [comment]
I fixed this bug yesterday. I found that the pseudo-element was not taking effect, so I added some code, and it is now working.
![4675957a-4794-4314-b579-d607888d2029](https://github.com/user-attachments/assets/0ea7f456-f4da-4809-8e20-d7c48d21c406)
![cffd5d78-1474-439b-a6f3-d18948eb93e3](https://github.com/user-attachments/assets/82e3ef4e-437c-4569-87ec-458279f6e78d)

**Comment by itsarghyadas** [comment]
oh nice to know that it is now working. And thanks for providing the fix too.

**Comment by itsarghyadas** [comment]
I just checked the component, and the default version works fine for both `copy-paste` and the `CLI` If you want to use it as a `buttonVariants` that also works if you add the rainbow variant in the code.
