### ISSUE TITLE
Retro Grid lines are not clear in the dark mode

### ISSUE THREAD

**Issue by alamenai** [magicuidesign/magicui#441]
I switched to the dark mode and I noticed that the lines of the Retro Grid did not change their colors ( I expected them to be lighter )

![image](https://github.com/user-attachments/assets/58621573-c6a3-4f5b-bd80-9086a03fdc72)

At least similar to these lines:

![image](https://github.com/user-attachments/assets/a8a265f1-6b88-4344-a063-1641f4c24776)

**Comment by dillionverma** [comment]
fixed! https://github.com/magicuidesign/magicui/commit/73ed34c41f047921aaec6654a6b1f1032ba01ed9
