### ISSUE TITLE
`ShinyButton` misses the default button props

### ISSUE THREAD

**Issue by alamenai** [magicuidesign/magicui#443]
When I started using Shiny Button, and I wanted to add `onClick` event, I noticed it missed the default button props ( HMTLButtonProps ):

![image](https://github.com/user-attachments/assets/6a246be1-4fd1-48d2-9803-cb9ed73398df)

The props should inherit the button element interface with the custom props:

![image](https://github.com/user-attachments/assets/ef91b93f-ce0a-4b83-9b37-fbd80fc0bfa5)

> This was just a quick thought.

Like this, we can find the default props:

![image](https://github.com/user-attachments/assets/f1c5ffba-9345-49b7-b497-85083ee3d2e0)

**Comment by dillionverma** [comment]
Hey! I would check the latest code as I think we addressed this :) Closing issue for now.
