### ISSUE TITLE
[effect] shine border

### ISSUE THREAD

**Issue by dillionverma** [magicuidesign/magicui#46]
https://codepen.io/matthewgoshman/pen/bGMpKZy

This one is awesome! Would be sweet to recreate this in react / typescript with props for configurability.

## Requirements:
- [ ] light/dark mode support
- [ ] typescript props for configurability

Please assign issue to yourself or comment below if you want to tackle this :)

Also we must credit original author!

**Comment by unnamed-lab** [comment]
Can I work on this?

**Comment by unnamed-lab** [comment]
I believe I have accomplished the task.

Let me know what you think - https://github.com/magicuidesign/magicui/pull/94

**Comment by dillionverma** [comment]
done!
