### ISSUE TITLE
Why the morphing text component animation is different in Mozilla?

### ISSUE THREAD

**Issue by alamenai** [magicuidesign/magicui#460]
**Describe the bug**

I started using the [Morphing Text](https://magicui.design/docs/components/morphing-text) but I noticed that its behavior is different from a browser to another browser.

**To Reproduce**
1. Go to [Morphing Text](https://magicui.design/docs/components/morphing-text)
2. Open the link in Mozilla and Google.

**Expected behavior**
Same animation behavior.

**Current behavior**
Different animation behavior.

**Comment by itsarghyadas** [comment]
Thanks for the catch! We fixed it here https://github.com/magicuidesign/magicui/pull/469
