### ISSUE TITLE
[bug]: /docs/components/icon-cloud

### ISSUE THREAD

**Issue by sakthii05** [magicuidesign/magicui#464]
**Describe the bug**
The Icons are in default black colour, 

**Expected behavior**
The Icons should be respective to their Icon colour.

**Comment by itsarghyadas** [comment]
Hey, we’re aware of this issue. We tried debugging it and discovered it likely comes from a 3rd-party library. We still want to fix this as soon as possible, and we’re actively working on it. Please give us some time to figure out a solution. Thank you for your feedback!

**Comment by dillionverma** [comment]
duplicate of #465
