### ISSUE TITLE
[bug]: /docs/components/icon-cloud

### ISSUE THREAD

**Issue by Appifyo** [magicuidesign/magicui#465]
Previously, the icons in the interactive cloud were displayed in their intended colors, but now they appear blackish. Additionally, they behave strangely on page reloads, such as not maintaining their state or appearing incorrectly.

<img width="666" alt="Screenshot 2024-12-25 at 1 09 17 AM" src="https://github.com/user-attachments/assets/c67f7206-032f-4c8f-8ac7-54230b7e4000" />
<img width="820" alt="Screenshot 2024-12-25 at 1 09 44 AM" src="https://github.com/user-attachments/assets/2858825e-9f58-4c5e-ae12-c1ad443818e4" />

**Comment by Harisafzal03** [comment]
I am facing the same issue can you please cover it.

**Comment by itsarghyadas** [comment]
Hey, we’re aware of this issue. We tried debugging it and discovered it likely comes from a 3rd-party library. We still want to fix this as soon as possible, and we’re actively working on it. Please give us some time to figure out a solution. Thank you for your feedback!

**Comment by dillionverma** [comment]
Working on a fix for this everyone!

**Comment by EngenMe** [comment]
I have created a pull request for that issue, with relevant unit test to it, I wish it will accepted by authors.
Regards

**Comment by dillionverma** [comment]
cheers 🍻

Thanks @EngenMe and @teaguestockwell
