### ISSUE TITLE
[component] Rotating circles on scroll

### ISSUE THREAD

**Issue by dillionverma** [magicuidesign/magicui#47]
https://x.com/learnframer/status/1754905348413194638

https://github.com/magicuidesign/magicui/assets/16860528/523192cb-d0ec-4805-95f7-a41e00f89936

This one is awesome! Would be sweet to recreate this in react / typescript / framer motion with props for configurability.

Please assign issue to yourself or comment below if you want to tackle this :)

Also we must credit original author!!

**Comment by DoffuXx** [comment]
can you assign me  this one

**Comment by dillionverma** [comment]
Closing for now as it's gone stale and no good implementation yet
