### ISSUE TITLE
[button] - New Pulsating Button

### ISSUE THREAD

**Issue by dillionverma** [magicuidesign/magicui#48]
beautiful button here 😍

https://github.com/magicuidesign/magicui/assets/16860528/17508677-6119-42ed-bd37-fb8ea361e30f

we should re-create this in react + typescript + tailwindcss :)

**Comment by NoubissiViany** [comment]
@dillionverma Please assign this task to me

**Comment by dillionverma** [comment]
how's progress on this @NoubissiViany ?

**Comment by NoubissiViany** [comment]
Having difficulty in installing pnpm in my machine

**Comment by shikhap04** [comment]
@dillionverma I would love to help if possible!

**Comment by dillionverma** [comment]
go for it @shikhap04 ill assign to you for now

**Comment by dillionverma** [comment]
let me know if you need help @NoubissiViany

**Comment by shikhap04** [comment]
Hey @dillionverma, let me know if there needs to be any changes, otherwise I can make a PR.

https://github.com/magicuidesign/magicui/assets/116731555/ed1675e1-5557-44e4-b7f3-0e92d3046e73

**Comment by dillionverma** [comment]
Looking good! 

Small thing I noticed is to make sure border radius is somehow same for the pulse and the button itself

This image should help but I'm not sure what the implmentation would look like without looking at code

![image](https://github.com/magicuidesign/magicui/assets/16860528/99dbfb2f-9ffa-4a39-8e61-8be73719eadc)

Also the easing function looks a little bit off? Might need to play around with either linear or ease-out function to get that nice aesthetic ✨

**Comment by dillionverma** [comment]
Closing issue since its done!
