### ISSUE TITLE
[Developer Experience] We need a Magic UI CLI!

### ISSUE THREAD

**Issue by dillionverma** [magicuidesign/magicui#49]
Something just like this would be amazing! https://ui.shadcn.com/docs/cli

We should be able to install magicui directly from the cli

## Ideal Developer Experience Flow

1. 

```
npx magicui@latest init
```

2. 

```
npx magicui@latest add border-beam
```

## How to start?

Read through the shadcn cli and how it was first implemented for the MVP https://github.com/shadcn-ui/ui/pull/112
Read through the current cli package and see how it was improved https://github.com/shadcn-ui/ui/tree/main/packages/cli
Implement the same foundation here :)

**Comment by divyamdotfoo** [comment]
assigned!

**Comment by Ianduha13** [comment]
@divyamdotfoo @dillionverma Yesterday I was thinking just about this, it would be excellent for the project. If you need some help, I would love to collaborate on this task

**Comment by dillionverma** [comment]
Marking as closed for now since this is done!
