### ISSUE TITLE
Letter pullup preview text not visible in dark mode

### ISSUE THREAD

**Issue by navjot369** [magicuidesign/magicui#51]
Preview text of "Staggered Letter Pull Up Animation" is not visible when dark mode is enabled. This may be due to an error in the `className`

<img width="1097" alt="Screenshot 2024-05-24 at 8 43 40 PM" src="https://github.com/magicuidesign/magicui/assets/109858950/8d766f17-036b-4545-b73c-183c8f240d91">

Here's the corrected version:

<img width="1101" alt="Screenshot 2024-05-24 at 8 45 04 PM" src="https://github.com/magicuidesign/magicui/assets/109858950/276be5c7-800a-4ee9-b600-509464d0ec3f">

I'd like to be assigned this issue, please.

**Comment by dillionverma** [comment]
assigned!
