### ISSUE TITLE
Magic UI for JS / HTML

### ISSUE THREAD

**Issue by darkylmnx** [magicuidesign/magicui#60]
Any plans to have a React-free version in Vanilla JS or WC for compatibility with other frameworks like Vue, Svelte etc?

**Comment by dillionverma** [comment]
yes it's possible but I'm going to need help from the community!


For Vue, Svelte and HTML we need to port the framer-motion dependency to https://motion.dev


I'll write up a detailed outline later when I get more time.

Feel free to take initiative though!

**Comment by PolyAtomicIon** [comment]
Hi, I would like to take the initiative, where can I start first to support Vue3?

**Comment by georgebrianb** [comment]
@PolyAtomicIon How is this going? I would love to have access to such a library in Vue

**Comment by LeeKrane** [comment]
@PolyAtomicIon any updates? Thanks in advance

**Comment by PolyAtomicIon** [comment]
Nope, no progress unfortunately, it is better to do it from scratch ...

**Comment by dillionverma** [comment]
Following up on this 

Will be difficult for myself to maintain separate libraries for other frameworks but there are a ton of great community options already!

Vue:
https://inspira-ui.com/
https://spark-ui.dev/

Svelte:
https://animation-svelte.vercel.app/magic

Closing issue for now

**Comment by phadaphunk** [comment]
@dillionverma Know of any good alternatives for VanillaJS? This is sick
