### ISSUE TITLE
The icon on the "Browse Components" button doesn't work on hover.

### ISSUE THREAD

**Issue by itsarghyadas** [magicuidesign/magicui#65]
As you can see in the video, when you hover over the "Browse Components" button, the `<ChevronRight/>` icon should translate to the right a little bit. However, this isn't happening.

https://github.com/magicuidesign/magicui/assets/89768406/50bc23cf-0278-4102-b495-7dbb74c867fb

**Comment by dillionverma** [comment]
fixed with #68
