### ISSUE TITLE
[Special Effect] Neon Gradient Underglow

### ISSUE THREAD

**Issue by dillionverma** [magicuidesign/magicui#70]
https://codepen.io/Unleashed-Design/pen/MWOaPGL

We should recreate this in react + typescript + tailwindcss and credit the original author! 

This would be an amazing addition to the magicui community :) 

Please comment below if you are interested to take this on so we can assign this to you

https://github.com/magicuidesign/magicui/assets/16860528/8480b07e-556e-4ebc-a683-59c74c480091

**Comment by Draxx0** [comment]
Hello, well, I'll try to do this, do we stop at the "simple card" or do we add the content as well? CardTitle, CardDescription & more ? @dillionverma 

Have a nice day :D

**Comment by dillionverma** [comment]
This is awesome!! Lets leave it just at simple card for now and let other developers use it as they wish :)

**Comment by dillionverma** [comment]
fixed by #83
