### ISSUE TITLE
[Special Effect] Confetti Animations!

### ISSUE THREAD

**Issue by dillionverma** [magicuidesign/magicui#71]
Confetti??? 🎉

We should definitely have some nice, clean, tasteful, and easy to use confetti animations that devs can just import into their products. 

Every person should be able to do this easily.

For example, I like the clean one shown here.

https://wope.com/

We should credit everyone who we take inspiration from!

https://github.com/magicuidesign/magicui/assets/16860528/f9a2615c-f6d6-4fcf-b749-bfedcacc120f

**Comment by BankkRoll** [comment]
Was making some today myself, came a crossed [canvas-confetti](https://github.com/catdad/canvas-confetti). Similar or maybe their source, adding for inspo.


https://github.com/magicuidesign/magicui/assets/106103625/a43e7bac-3bb5-42af-beb2-22a1c5533861

**Comment by dillionverma** [comment]
Thanks for sharing! Here's one more I'll add to the mix.

https://github.com/herrethan/react-confetti-explosion

I would love if someone could put some thought into this to optimize performance and developer experience while minimizing dependencies

**Comment by pilladipesh33** [comment]
Is it suggested to add a to third party package ?

**Comment by dillionverma** [comment]
i think third party package is fine if its lightweight and well maintained. use your best judgement imo

**Comment by dillionverma** [comment]
This is done! Closing for now
