### ISSUE TITLE
[background] Warp animation

### ISSUE THREAD

**Issue by dillionverma** [magicuidesign/magicui#72]
https://x.com/jh3yy/status/1732553845530566855?s=20

This one is really cool and could be used as a subtle background animation

we should convert this to react + typescript + tailwindcss and make it easy to use with props

also credit the original author for inspiration!

**Comment by pilladipesh33** [comment]
This looks cool I would I'd be interested can you assign it to me

**Comment by tomonarifeehan** [comment]
I can work on this.

**Comment by tomonarifeehan** [comment]
I removed the css variables and unnecessary lines of code from the demo.

Maybe someone can pick up where I left off.

[index.txt](https://github.com/user-attachments/files/15519604/index.txt)
[script.txt](https://github.com/user-attachments/files/15519605/script.txt)
[style.txt](https://github.com/user-attachments/files/15519606/style.txt)

**Comment by vhespanha** [comment]
Can i take this one?

**Comment by tomonarifeehan** [comment]
> Can i take this one?

Yes, I completely forgot about this. I'm not working on it.

**Comment by ParagGhatage** [comment]
@dillionverma 
I have started working on this.
Would you assign me this?
I will deliver a pull request in few days.

**Comment by lukenguyen-me** [comment]
@dillionverma  @tomonarifeehan 
How is this going?
I have a PR ready for this so could you assign me this if it's available?

**Comment by itsarghyadas** [comment]
@lukenguyen-me thanks for the PR! We’ve merged it, so I’m closing this issue in favor of PR #307
