### ISSUE TITLE
[component] Hero Video Component

### ISSUE THREAD

**Issue by dillionverma** [magicuidesign/magicui#73]
We need to make a hero video component

Similar Demo here: https://wope.com

## Requirements:
- [ ] Click on play button to open modal/dialog which plays a video
- [ ] Should ideally be customizable with props

![image](https://github.com/magicuidesign/magicui/assets/16860528/0e5fe56c-759d-474a-b50f-d3a618a893ca)

**Comment by unnamed-lab** [comment]
I think I could give this a shot 👀

**Comment by dillionverma** [comment]
yass!

**Comment by 0xRaduan** [comment]
This is so much needed!

**Comment by dillionverma** [comment]
This is done!
https://magicui.design/docs/components/hero-video-dialog
