### ISSUE TITLE
Magic UI for VueJS 

### ISSUE THREAD

**Issue by dillionverma** [magicuidesign/magicui#75]
I'm making this issue to track any ports of Magic UI components to VueJS

If you have any ports, feel free to comment them below to share with the community!

We will eventually try and merge everything together in one repo if possible down the line.

However our current priority will be on react first. 

If someone from the community wants to take initiative to integrate VueJS support into this repo please feel free to comment below and get started :) No permission needed

**Comment by hjardines** [comment]
👍

**Comment by nabilkrs** [comment]
We are waiting for Vuejs support

**Comment by Aurion72** [comment]
Need this :D

**Comment by saibimajdi** [comment]
tik tok... tik tok...
