### ISSUE TITLE
Having a declared packageManager in the package.json is creating issues with other versions of pnpm.

### ISSUE THREAD

**Issue by itsarghyadas** [magicuidesign/magicui#78]
![packageManager](https://github.com/magicuidesign/magicui/assets/89768406/bdc6a345-fec6-4086-82cd-2e44e8195be2)

![pnpm-version-error](https://github.com/magicuidesign/magicui/assets/89768406/6c6a2cff-5c52-493c-8c20-e6e2ed5e8f85)

Is it necessary to declare the `packageManager` version in the `package.json`? If I have a different version of `pnpm` installed on my system, it causes an error. I believe we can remove this or make it less restrictive. Let me know your thoughts @dillionverma

**Comment by unnamed-lab** [comment]
I faced this error a while back and had to downgrade the pnpm manager version I had installed before it could work. Is the strict pnpm version necessary?

**Comment by dillionverma** [comment]
removed the declared package manager on main!
