### ISSUE TITLE
[HELP NEEDED] Need help spreading the word about Magic UI!

### ISSUE THREAD

**Issue by dillionverma** [magicuidesign/magicui#86]
Hi friends :) 

I'd love your help to spread the word about Magic UI as far as possible!

If you share it somewhere please comment it below so we can keep track :)

## Ideas:
- [ ] Submit PRs referencing Magic UI to 100+ awesome lists. Some examples below:
  - [ ] https://github.com/brillout/awesome-react-components
  - [ ] https://github.com/aniftyco/awesome-tailwindcss
  - [ ] https://github.com/unicodeveloper/awesome-nextjs
  - [ ] https://github.com/anubhavsrivastava/awesome-ui-component-library
  - [ ] https://github.com/gztchan/awesome-design
- [ ] Newsletters Features
  - [ ] https://console.dev/
- [ ] Youtube videos
- [ ] Any other ideas??

**Comment by BankkRoll** [comment]
https://github.com/anubhavsrivastava/awesome-ui-component-library/pull/25

**Comment by dillionverma** [comment]
you are awesome 🙌

**Comment by tomonarifeehan** [comment]
Maybe share here:

https://goodfirstissue.dev

I don't know if anyone looks at this site though lol

**Comment by safethecode** [comment]
> https://news.ycombinator.com/

**Comment by dillionverma** [comment]
tysm - i just contacted ed @tomonarifeehan 

looks like hackernews got hit last week too @safethecode

**Comment by safethecode** [comment]
> tysm - i just contacted ed @tomonarifeehan
> 
> looks like hackernews got hit last week too @safethecode

I posted it on GeekNews, which is like HackerNews in Korea, and it's getting a lot of attention :)

**Comment by dillionverma** [comment]
haha the comments have valid feedback 😄

looks like the landing page is a bit confusing

thanks for sharing @safethecode!

**Comment by dillionverma** [comment]
Closing for now! Thanks for the support everyone :)
