### ISSUE TITLE
The GitHub icon is not showing when displaying the number of GitHub stars

### ISSUE THREAD

**Issue by itsarghyadas** [magicuidesign/magicui#90]
Before showing the number ---
![before-showing-number](https://github.com/magicuidesign/magicui/assets/89768406/d2192093-40c0-4c7c-9b48-1efb221993aa)

After showing the number ---
![after-showing-number](https://github.com/magicuidesign/magicui/assets/89768406/e2371418-0e62-4d8a-a088-fd9724f6acff)

As you can see, the GitHub icon is almost hidden when the number of GitHub stars is visible. You may need to adjust the max-width to fix this issue.

Thanks,
Arghya

**Comment by achrafrzz1** [comment]
Yes, I see that when the numbers appear, the icon is displayed. I will try to fix it.

**Comment by itsarghyadas** [comment]
Assigning it to you.

**Comment by achrafrzz1** [comment]
@itsarghyadas  received.

**Comment by dillionverma** [comment]
done
