### ISSUE TITLE
[button] Animated Subscribe Button

### ISSUE THREAD

**Issue by dillionverma** [magicuidesign/magicui#92]
This animation is dope!

https://codesandbox.io/p/sandbox/laughing-morning-cjvkxd?file=%2FApp.tsx%3A33%2C20&utm_medium=sandpack

https://github.com/magicuidesign/magicui/assets/16860528/75389cd4-a561-462f-b4a4-800644125c52

We should remove the chakra dependency and make a simple configurable button with react + typescript + framer motion + tailwindcss :)

Comment below if you are taking this on!

**Comment by pilladipesh33** [comment]
I would like to contribute to this

**Comment by pilladipesh33** [comment]
Just one question for icons should I use lucide react or img link

**Comment by pilladipesh33** [comment]
Hey @dillionverma  I have done the part here the final overview if there anything else you want to let me and if not I'll raise the PR

https://github.com/magicuidesign/magicui/assets/99866329/61664812-c6c2-4755-8c3b-2e10eccb6e6c

**Comment by dillionverma** [comment]
this looks pretty good already haha send the PR! @pilladipesh33

**Comment by pilladipesh33** [comment]
@dillionverma  I have created the PR check it once and allow it

**Comment by dillionverma** [comment]
great work! marking as done
