### ISSUE TITLE
[HELP] Discord community for MagicUI library

### ISSUE THREAD

**Issue by Wellitsabhi** [magicuidesign/magicui#95]
# Magic UI Library Discord Server Proposal

## Purpose
Create a dedicated Discord community for developers and users of the Magic UI library to enhance communication and collaboration.

### General Channels
- `#welcome`: Introductions and rules.
- `#announcements`: Official updates.

### Developer Channels
- `#dev-general`: Developer discussions.
- `#dev-help`: Support for developers.
- `#dev-collaboration`: Find collaborators.

### User Channels
- `#user-general`: User discussions.
- `#user-showcase`: Project showcases.
- `#user-support`: Support for users.
- `#user-feedback`: User feedback.

### Resource Channels
- `#resources`: Documentation and tutorials.
- `#community-resources`: User-created resources.

### Off-topic Channels
- `#off-topic`: Non-technical discussions.
- `#memes`: Fun content.

## Roles and Permissions
- **Admin**: Full control.
- **Moderator**: Manage and moderate.
- **Developer**: Access developer channels.
- **User**: Access user channels.
- **Guest**: Limited access.

## Guidelines
- **Respectful Communication**: Be inclusive and respectful.
- **No Spam**: Keep channels relevant.
- **Support Etiquette**: Provide clear questions and context.

**Comment by Wellitsabhi** [comment]
i would be happy to make it @dillionverma . Just assign it to me.

**Comment by Wellitsabhi** [comment]
Discord  server here  - https://discord.gg/Y5YTZTue

**Comment by itsarghyadas** [comment]
@Wellitsabhi we already have a discord server - https://magicui.design/discord

Thanks,
Arghya
