### ISSUE TITLE
Misalignment of "Installation" in table of contents

### ISSUE THREAD

**Issue by shubh73** [magicuidesign/magicui#96]
The `Installation` item in the table of contents seems to be incorrectly aligned, causing unnecessary spacing. I'm guessing that it's probably not at the same level as the other contents (as in nested), I could be wrong though.

<img width="296" alt="Screenshot 2024-05-28 at 1 02 46 PM" src="https://github.com/magicuidesign/magicui/assets/83606943/ddeccda6-f6ee-4842-88f3-24596f65644a">

**Comment by dillionverma** [comment]
great point and yes it does look misaligned and not on the same level

we can address this

**Comment by dillionverma** [comment]
happy to take any PRs for this if anyone wants to tackle it!

**Comment by gokh4nozturk** [comment]
I am on it @dillionverma

**Comment by dillionverma** [comment]
tysm @gokh4nozturk 

merged
