### ISSUE TITLE
Interactive Icon Cloud error

### ISSUE THREAD

**Issue by Maulanya** [magicuidesign/magicui#98]
[

https://github.com/magicuidesign/magicui/assets/81512862/5134dfaf-8627-4a80-b61a-fefc7ef7951f

](url)

**Comment by unnamed-lab** [comment]
That's strange... it works fine for me though

**Comment by prakashsp23** [comment]
whats ur maxspeed?

**Comment by Maulanya** [comment]
> whats ur maxspeed?

i dont change the speed

**Comment by Maulanya** [comment]
The problem is solved, by placing components that do not have hooks in them

**Comment by Maulanya** [comment]
> [
> 
>  2024-05-28.19-23-20.mp4 
> ](url)
The problem is solved, by placing components that do not have hooks in them

**Comment by Maulanya** [comment]
> [
> 
>  2024-05-28.19-23-20.mp4 
> ](url)

The problem is solved, by placing components that do not have hooks in them
